### ISSUE TITLE
Unexpected results from dodgr_paths

### ISSUE THREAD

**Issue by JimShady** [ATFutures/dodgr#100]
Hi,

I am trying to use OSM data and dodgr to produce isochrone-type data. I want to select a starting point, and then generate all the routes on the network from that point that are within 500 metres. I would like to have the actual lines, and then draw them onto a map (rather than a polygon which isochrone tools typically return).

I have written a reproducible example below. It generates routes between a starting point, and other points on the network. I then plot one of the routes, but it is not a route. I'm not sure why.

I suspect that I misunderstand something rather than an error with the library .... ?

Thanks as always.

```r
rm(list=ls())

library(osmdata)
library(dodgr)
library(tidyverse)
library(sf)

origin <- c(-0.134722, 51.510115)
# Get the start point that we want to use

# Make a spatial object of the start point
point           <- tibble(id = '1', x  = origin[1], y  = origin[2]) %>%
                    st_as_sf(coords = c("x", "y"), crs = 4326) %>%
                    mutate(x = origin[1],
                           y = origin[2])

# Get the osm network for a 100m radius of the point
net             <- opq(bbox =  st_bbox(st_transform(st_buffer(st_transform(point, 27700), 100), 4326))) %>%
                        add_osm_feature(key = 'highway') %>%
                        osmdata_sf() %>%
                        pluck('osm_lines') %>%
                        select(osm_id, highway, geometry)

# Make a routing network out of the streets in that area
graph           <- weight_streetnet(net, wt_profile = 'foot') %>%
                        filter(component == 1)

# Check it looks ok
ggplot(net) + geom_sf()

```

![image](https://user-images.githubusercontent.com/2901470/63161833-f09bc800-c018-11e9-8ac9-b6b540e6b4ec.png)

```r


# Do routing from the start point we specified, to every other node in the network we
# have downloaded, then discard all results where the total routed distances is greater than 500 metres
route_distances <- dodgr_dists(graph, from = origin) %>%
                    list(from = rownames(.)[row(.)] %||% row(.),
                         to = colnames(.)[col(.)] %||% col(.),
                         distance = .) %>%
                    map_dfc(as.vector) %>%
                    filter(distance <= 500)

# So we now have the start and end nodes for journeys that are less than 500m, but we want to know the routes.

# This is where we will put our results
route_results <- list()

# Go through each row of your input table and do the routing
for (i in 1:nrow(route_distances)) {

    list_of_graph_edges     <- dodgr_paths(graph,
                                   from   = route_distances[i,]$from,
                                   to     = route_distances[i,]$to,
                                   vertices = FALSE)[[1]][[1]]

    route_results[[i]]      <- list_of_graph_edges

}

# So each item in the route_results list corresponds to one of the journeys we wanted to route.
nrow(route_distances)
length(route_results)

# Let us plot one of the routes that has been generated.

graph[graph$edge_id %in% route_results[[1]],] %>%
    left_join(data.frame(edge_id = route_results[[1]]), .) %>%
    left_join(., net, by = c('way_id' = 'osm_id')) %>%
    select(edge_id, d, geometry) %>%
    st_as_sf() %>%
    ggplot() +
    geom_sf()
```

![image](https://user-images.githubusercontent.com/2901470/63161871-0b6e3c80-c019-11e9-8933-a033cbfd0266.png)

This doesn't look correct. It's not a route. Why not? I was expecting a line from our starting point.

**Comment by JimShady** [comment]
Ok. Upon further investigation I think I understand what is happening. To visualize the routes I need to make my 'graph' above, into a sf object.

```r
> graph
   geom_num edge_id    from_id   from_lon from_lat      to_id     to_lon   to_lat         d
1         1       1   25257657 -0.1361479 51.51119 3357928883 -0.1355765 51.51073 64.575283
2         1       2 3357928883 -0.1355765 51.51073   25257657 -0.1361479 51.51119 64.575283
3         1       3 3357928883 -0.1355765 51.51073     107820 -0.1355377 51.51070  4.339291
4         1       4     107820 -0.1355377 51.51070 3357928883 -0.1355765 51.51073  4.339291
5         2       5     107820 -0.1355377 51.51070 2465838818 -0.1350526 51.51074 33.868194
6         2       6 2465838818 -0.1350526 51.51074     107820 -0.1355377 51.51070 33.868194
7         2       7 2465838818 -0.1350526 51.51074 3729216344 -0.1348423 51.51075 14.654238
8         2       8 3729216344 -0.1348423 51.51075 2465838818 -0.1350526 51.51074 14.654238
```

If I add a `geometry` column to the above, I can then use this to visualize my results. I will attempt it now and report back ...

**Comment by JimShady** [comment]
Played around with this today, but still confused by what dodgr_paths is generating. 

Here's an example that is very similar to the above, but the `graph` has been made into a SF line object and the routes plotted.

```r
rm(list=ls())

library(osmdata)
library(dodgr)
library(tidyverse)
library(sf)

origin <- c(-0.134722, 51.510115)
# Get the start point that we want to use

# Make a spatial object of the start point
point           <- tibble(id = '1', x  = origin[1], y  = origin[2]) %>%
                    st_as_sf(coords = c("x", "y"), crs = 4326) %>%
                    mutate(x = origin[1],
                           y = origin[2])

# Get the osm network for a 100m radius of the point
net             <- opq(bbox =  st_bbox(st_transform(st_buffer(st_transform(point, 27700), 100), 4326))) %>%
                        add_osm_feature(key = 'highway') %>%
                        osmdata_sf() %>%
                        pluck('osm_lines') %>%
                        select(osm_id, highway, geometry)

# Make a routing network out of the streets in that area
graph           <- weight_streetnet(net, wt_profile = 'foot') %>%
                        filter(component == 1)

# Check it looks ok
ggplot(net) +
    geom_sf() +
    geom_sf(data = point, col = 'red')


# Do routing from the start point we specified, to every other node in the network we
# have downloaded, then discard all results where the total routed distances is greater than 500 metres
route_distances <- dodgr_dists(graph, from = origin) %>%
                    list(from = rownames(.)[row(.)] %||% row(.),
                         to = colnames(.)[col(.)] %||% col(.),
                         distance = .) %>%
                    map_dfc(as.vector) %>%
                    filter(distance <= 500)

# So we now have the start and end nodes for journeys that are less than 500m, but we want to know the routes.

# This is where we will put our results
route_results <- list()

# Go through each row of your input table and do the routing
for (i in 1:nrow(route_distances)) {

    list_of_graph_edges     <- dodgr_paths(graph,
                                   from   = route_distances[i,]$from,
                                   to     = route_distances[i,]$to,
                                   vertices = FALSE)[[1]][[1]]

    route_results[[i]]      <- list_of_graph_edges

}

# So each item in the route_results list corresponds to one of the journeys we wanted to route.
nrow(route_distances)
length(route_results)

## Make linestrings from the graph network

b = graph[, c('from_lon', 'from_lat')]
names(b) = c("long", "lat")
e = graph[, c('to_lon', 'to_lat')]
names(e) = c("long", "lat")

graph$geometry = do.call(
    "c",
    lapply(seq(nrow(b)), function(i) {
        st_sfc(
            st_linestring(
                as.matrix(
                    rbind(b[i, ], e[i, ])
                )
            ),
            crs = 4326
        )
    }))

graph = st_as_sf(graph)


# Let us plot one of the routes that has been generated.

ggplot(graph[graph$edge_id %in% route_results[[1]],]) +
    geom_sf()

# This doesn't look correct. It's not a route. Why not? I was expecting a line from our starting point.

```

![image](https://user-images.githubusercontent.com/2901470/63170212-b9391580-c030-11e9-8cf6-9b0a5d34d0f8.png)

**Comment by JimShady** [comment]
Now realised that I should be perhaps using the `route_dodgr` function from the `stplanr` package for this work. Considering how to integrate it now.

**Comment by mpadge** [comment]
Thanks for all the input James, and great to have your input again. This an issue that has been effectively addressed elsewhere, but not incorporated within `dodgr`. It is very easily dealt with at the C++ level, but very difficult if not effectively impossible, at the R level. Isochrones and isodists have long been planned (#59), but I've been (intentionally) delaying the implementation. But the time is probably ripe for doing this, and your example provides a nice extension of standard isodist/chrone analyses. Any input you could offer throughout this implementation would be great!

And so, for the sake of clarity: A "standard" isodist/isochrone is a polygon constructed by tracing all paths from an origin point and finding, at the end of each possible path, the last point that is within the specified distance/time. Is what you are desiring then effectively just the list of all paths traced back from each of those terminal points? If so, that would be very straightforward to implement. I hadn't thought of this before, but imagine it may be of quite general utility, so it would be a cool extension. I imagine something like `dodgr_isodist()` and `dodgr_isochrone()` functions with an additional parameter, `dodgr_isodist(..., return_paths = FALSE)`, where `return_paths = TRUE` would return your desired list of paths, but default would be a simple polygon. Would that suffice?

If so, we could close this issue, and move on over to #59. Let me know whether there are any other outstanding issues separate from that issue that you'd like resolved here.

**Comment by mpadge** [comment]
Another thought: Is your problem associated with your analyses of tube trips? Because my [`grfs-router` package](https://github.com/atfutures/gtfs-router) makes isochrones, but uses GTFS data, while TfL uses their own format. A side project I'll implement one day is conversion of the TfL format to GTFS standard, which would open up lots of possibilities of applying general GTFS tools to TfL data.

**Comment by JimShady** [comment]
Hi Mark,

Just been reading #59 and your comments above. Thank you. I think something like `dodgr_isodist(origin, distance, return_paths = TRUE)` is what I'm looking for. I made a rough hacky way of doing it this morning in the meantime, see code below (note it will take a few minutes to run).

This isn't to do with tube lines. I'm looking at the type of use case/scenario where you say that Person A starts at coordinates X,Y, and you have 2 minutes to catch them. They can run in any direction along the street network. Given 5 police offices, where would be the best place for the police officers to go, to attempt to intercept the person?

I figured doing some isochrone paths would be a decent start. Then looking at key intersections or something like that.

```r
# Start with a clear env
rm(list=ls())

# Libraries
library(osmdata)
library(dodgr)
library(tidyverse)
library(sf)
library(stplanr)

# Get the start point that we want to use
origin          <- c(-0.134722, 51.510115)

# Make a spatial object of the start point
point           <- tibble(id = '1',
                          x  = origin[1], y  = origin[2]) %>%
                          st_as_sf(coords = c("x", "y"), crs = 4326) %>%
                          mutate(x = origin[1], y = origin[2])

# Make a bounding box of 600 metres around the starting point, and get the OSM network for that area
mynet           <- opq(bbox =  st_bbox(st_transform(st_buffer(st_transform(point, 27700), 600), 4326))) %>%
                    add_osm_feature(key = 'highway') %>%
                    osmdata_sf() %>%
                    pluck('osm_lines') %>%
                    select(osm_id, highway, name, lanes, maxspeed, geometry)

# Point density on the network to sample
point_density   <- 1/10

# Sample a load of points
dest_points     <- st_line_sample(st_transform(mynet, 27700), density = point_density) %>%
                    st_transform(4326) %>%
                    st_cast('POINT')

dest_points      <- matrix(st_coordinates(dest_points), ncol = 2)

# want to make a matrix of the origin points. Couldn't do it until we knew how many dest points.
start_matrix    <- point %>%
                    slice(rep(1:n(), each=nrow(dest_points))) %>%
                    st_drop_geometry() %>%
                    select(x, y)

# Route from the starting point, to every point generated above
routes          <- route_dodgr(start_matrix,dest_points, net = mynet) %>%
                    mutate(dist = as.numeric(st_length(.))) %>%
                    filter(dist < 500)

# Plot the results (this needs work)
ggplot(routes) +
    geom_sf(size = 1, color=alpha("red",0.1))

# To finish this off I think I need to split the linestrings for each route,
# into individual lines, and then group_by and sum. I can then use the value for better vis.
```

![image](https://user-images.githubusercontent.com/2901470/63259462-605abe80-c276-11e9-9cdc-646a095d73bc.png)

**Comment by JimShady** [comment]
Closing this now. Thanks.

**Comment by mpadge** [comment]
@JimShady There's already a trial implementation of `dodgr_isodists()` that you could use. Currently only documented as a `man` entry (`?dodgr_isodists`). It's fully vectorized for optimal efficiency, and will calculate any number of origin points and distance isolines in a single calculation, returning `data.frame`s of destination points at nomiated isodistances. The following code could be used to get what you want:

``` r
res <- dodgr_isodists (graph, from, dlim = 500)
res <- res [[1]] [[1]] # current gives a list of lists; I'll likely change that today, so check
p <- dodgr_paths (graph, from = from, to = res$id)
```
That will give the OSM ID values along each path out to your specified isodistance limit.

Or, if you want a graph like the one you have above, just use `dodgr_flow_aggregate()` to aggregate from single origin to multiple destinations like this:
``` r
d <- dodgr_isodists (graph, from = from, dlim)
pts <- d [[1]] [[1]]
o <- names (d) [[1]]
dodgr_paths (graph, from = o, to = pts$id)
fmat <- matrix (1, nrow = 1, ncol = nrow (pts))
f <- dodgr_flows_aggregate (graph, from = o, to = pts$id, flows = fmat) %>%
    merge_directed_flows () %>%
    dodgr_to_sf ()
```

What I'll probably do now is change the list-of-lists object currently returned (first list for different origin points; second for different isodists) to a single `data.frame` with additional column names, so it can be directly fed into `filter` operations to extract desired data.

What I now *do not* think I'll do is an additional `return_paths` parameter, because that's a really fundamentally different type of return object, and one not really compatible with this form. It's also pretty straightforward to just do the above piping of `isodists %>% paths`, even though that is clearly less efficient. I nevertheless don't think at the moment that that will be too much of a penalty, because the calculation of isodists really is extremely efficient.

Hope that helps!

**Comment by JimShady** [comment]
Awesome @mpadge . I've got to work on something else for a day or two now, but will come back to this later in the week and have a go.

**Comment by JimShady** [comment]
Check this out @mpadge .... shouldn't the blue areas also have red lines in them, as you can get to them from the origin within 500 metres?

```r
# Start with a clear env
rm(list=ls())

# Libraries
library(osmdata)
library(devtools)
install_github('ATFutures/dodgr')
library(dodgr)
library(tidyverse)
library(sf)


# Get the start point that we want to use
origin          <- c(-0.578914, 44.847234)

# Make a spatial object of the start point
point           <- tibble(id = '1',
                          x  = origin[1], y  = origin[2]) %>%
                        st_as_sf(coords = c("x", "y"), crs = 4326) %>%
                        mutate(x = origin[1], y = origin[2])

# Make a bounding box of 600 metres around the starting point, and get the OSM network for that area
mynet           <- opq(bbox = st_bbox(st_transform(st_buffer(st_transform(point, 3857), 600), 4326))) %>%
                    add_osm_feature(key = 'highway') %>%
                    osmdata_sf() %>%
                    pluck('osm_lines') %>%
                    select(osm_id, highway, name, lanes, maxspeed, geometry) %>%
                    mutate(highway  = 'pedestrian',
                           lanes    = 2,
                           maxspeed = 50)

weighted_net    <- weight_streetnet(mynet, wt_profile = "foot")


buildings           <- opq(bbox = st_bbox(st_transform(st_buffer(st_transform(point, 3857), 600), 4326))) %>%
                        add_osm_feature(key = 'building') %>%
                        osmdata_sf() %>%
                        pluck('osm_polygons')

d <- dodgr_isodists(weighted_net, from = st_coordinates(point), 500)

fmat <- matrix (1, nrow = 1, ncol = nrow (d))

f <- dodgr_flows_aggregate (weighted_net, from = st_coordinates(point),
                            to = d$id,
                            flows = fmat) %>%
    merge_directed_flows () %>%
    dodgr_to_sf ()

ggplot(f) +
    geom_sf(data = st_crop(mynet,
                           st_bbox(st_transform(st_buffer(st_transform(point, 3857), 600), 4326)))) +
    geom_sf(data = f,
            col = 'red',
            size=1.5) +
    geom_sf(data = buildings) +
    geom_sf(data  =point, col = 'blue')

```
![image](https://user-images.githubusercontent.com/2901470/63598061-bd2be100-c5b6-11e9-80c0-a4b64fb79fc9.png)

**Comment by mpadge** [comment]
@JimShady The `dodgr_flows_aggregate` call in your code aggregates from the single origin to each isochrone point *along the shortest paths only*, not along all possible paths. The red lines merely represent these shortest paths to each terminal point, while the blue, alternative street segments do not trace any shortest path from your origin to any of the terminal points, and so are not included when you aggregate flows. Does that make sense?

**Comment by mpadge** [comment]
@JimShady The above commit fixes another minor :bug: that your code uncovered. The former version again returned your table `d` with `NA` values for `from`, because your `from = st_coordinates(point)` call yielded a 1-row matrix with a rowname, and that rowname was interpreted to be an OSM id, which in this case is incorrect. The "minor fix" is just a hack to fix this for the `dodgr_isodists` call, but nevertheless should work. Thanks!

**Comment by JimShady** [comment]
> @JimShady The `dodgr_flows_aggregate` call in your code aggregates from the single origin to each isochrone point _along the shortest paths only_, not along all possible paths. The red lines merely represent these shortest paths to each terminal point, while the blue, alternative street segments do not trace any shortest path from your origin to any of the terminal points, and so are not included when you aggregate flows. Does that make sense?

Yes, that makes sense. Thanks.

**Comment by JimShady** [comment]
Oh by the way @mpadge , I've been bugging you lots this last week or two because I'm trying to make this:

https://jimshady.shinyapps.io/IsoExclusionZones/

The code behind it is pretty ropey at the moment to be honest. I'll post it there soon, along with credit to dodgr package etc. It's work in progress.

**Comment by mpadge** [comment]
Nice! Keep me updated, and keep up the questions which are helping lots to improve `dodgr` code. Note that I've also managed to bundle a new [C++ implementation](https://github.com/joelgombin/concaveman) of [mapbox's concaveman](https://github.com/mapbox/concaveman) routine for concave hulls, which might be useful for your zone analyses. I haven't yet make these concave hull routines available for general use, but could easily do so if you need them. The algorithm is really *really* fast!

**Comment by JimShady** [comment]
This uses the concaveman package at the moment:

https://cran.r-project.org/web/packages/concaveman/index.html

**Comment by mpadge** [comment]
Yeah, but the problem with that is it's the old implementation which is in `.js`, and so that package needs depends on the monstrous installation of [`V8`](https://github.com/jeroen/v8). That makes it unworkable for many. The C++ implementation is much lighter (and I think much faster, but have [yet to benchmark](https://github.com/sadaszewski/concaveman-cpp/issues/5#issuecomment-511182844)).

**Comment by Urban-JonathanCohen** [comment]
@JimShady Do you know if route_dodgr takes into consideration the traffic direction?
im also finding difficult to translate the results from dodgr_paths to a real map again....
