### ISSUE TITLE
Images not displaying in the Vignettes

### ISSUE THREAD

**Issue by orlando-sabogal** [ATFutures/dodgr#106]
I think there is a problem with some images in the [Vignettes](https://atfutures.github.io/dodgr/articles/dodgr.html) section.  

I am seeing this: 

![Screenshot 2019-09-12 at 5 03 44 PM](https://user-images.githubusercontent.com/7365739/64824398-80cd1e80-d57f-11e9-9c41-caedd1180898.png)

![Screenshot 2019-09-12 at 5 03 52 PM](https://user-images.githubusercontent.com/7365739/64824404-86c2ff80-d57f-11e9-8232-01f097ca492f.png)

**Comment by mpadge** [comment]
This is #93 - I can't do anything about it, but might just write a note for the github vignette. The [CRAN version](https://cran.r-project.org/web/packages/dodgr/vignettes/dodgr.html) renders fine.
