### ISSUE TITLE
dodgr_dists not working from Vignette Example

### ISSUE THREAD

**Issue by orlando-sabogal** [ATFutures/dodgr#107]
I am trying to reproduce the following code from the [Vignette](https://atfutures.github.io/dodgr/articles/dodgr.html):

`bb <- osmdata::getbb ("york uk")`
`npts <- 1000`
`xy <- apply (bb, 1, function (i) min (i) + runif (npts) * diff (i))`

And when I run:

`d <- dodgr_dists (from = xy, to = xy, wt_profile = "foot", quiet = FALSE)`

I get this error: Error in dodgr_dists(from = xy, to = xy, wt_profile = "foot", quiet = FALSE) : 
  unused argument (wt_profile = "foot")

The documentation says: 

> Usage 
dodgr_dists(graph, from = NULL, to = NULL, shortest = TRUE,
  heap = "BHeap", parallel = TRUE, quiet = TRUE)

so I think is needed to pass the **graph** argument:  *data.frame or equivalent object representing the network graph (see Notes). * 
Also, **wt_profile** is not needed. 

In the [home](https://atfutures.github.io/dodgr/index.html) there is an example for **dodgr_dists()** which uses the **graph** argument. 

I have the feeling that this may be a typo in the Vignette. Or... am I missing something?

**Comment by mpadge** [comment]
Thanks @orlando-sabogal - that code was from a previous version of `dodgr` which automatically downloaded the entire network when no `graph` argument was provided. That is no longer done, but I had neglected to update the vignette. Now fixed :smile:
