### ISSUE TITLE
parallel 

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#11]
Coz the main C++ code is a loop. Easy to do; just has to be done in C++ and not in R

**Comment by mpadge** [comment]
This is actually quite difficult, and has been (hopefully temporarily) stopped with [this commit](https://github.com/ATFutures/dodgr/commit/045a1d240b5ceaeae0c6ec1f6c5adb4c39722def). The problem is that the `shared_ptr <Dijkstra>` object has to be shared amongst each core, yet each run changes the vertex lists ([`m_f` and `m_s`](https://github.com/ATFutures/dodgr/blob/master/src/dijkstra.h)), so parallel runs can't actually use the same `shared_ptr` object. Constructing new `shared_ptr <Dijkstra>` objects for each thread would remove any potential advantage of parallelisation, and so the whole idea has been stopped for the mo.

**Comment by virgesmith** [comment]
Told you parallelisation is hard ;)

If you share writable data between threads your code is no longer deterministic. Best approach is to share only const data, and make a copy of anything writable for each thread

**Comment by mpadge** [comment]
just cracked it. Unsurprisingly, precisely as you said. The trick was finding which objects could be held const, and exactly where within each thread to instantiate the `shared_ptr<Dijkstra>` object. That's all solved, and first tests show a 3.5x speed-up (with only 4 cores).

**Comment by mpadge** [comment]
Still have to parallelise flows (and this should be done before #32)

**Comment by mpadge** [comment]
@virgesmith Re-opening this issue to ask for some feedback from you:

The crucial function here which has ultimately **not** been parallelised is a function that aggregates over a single vector. The vector represents all the nodes of a network, and each parallel loop of this is a single Dijkstra run, with results then **added** to the vector of nodes. The only way I could think to parallelise this was to construct a huge matrix of `[nrows-by-nrows]`, so each column could be initialised to zero, columns filled in parallel, and then added at the end to give the desired aggregate result. This is crap, and slows things down so much holding such a huge matrix in memory that it's not worth doing.

My question to you: Have you ever encountered any situations like this previously, and would you perchance be able to suggest a more effective approach to parallelisation that might actually be worthwhile here? A simple "no" and closing of issue will suffice, but any constructive suggestions would be even better.

**Comment by mpadge** [comment]
Ah, okay, `parallelReduce` will do it, but I still don't immediately see how to do a `parallelReduce` on a vector sum. Any ideas there?

**Comment by virgesmith** [comment]
If it’s a big vector just split into n chunks, sum each chunk, then sum the sums. Is this not done for you under the hood?

(Don’t expect exactly the same answer as you’d get if you summed sequentially)

**Comment by mpadge** [comment]
Can't split the vector, alas, coz the whole thing has to be traced for each Dijkstra loop

**Comment by mpadge** [comment]
@virgesmith I'm pretty sure it can't be directly parallelised because aggregation into a single vector can never be broken into independent threads. I've got an exploratory repo where I've just implemented parallelisation by dumping intermediate results from each thread to a series of binary files and then re-aggregating these afterwards. (The [commit is here](https://github.com/ATFutures/m4ra/commit/bc9d571e86d4c5815ada7b203190baddeffd7211)). That was about the cleverest approach I could think of. I'll check how it scales before possibly implementing here.

**Comment by virgesmith** [comment]
link to commit doesnt work for me...

**Comment by mpadge** [comment]
oh yeah, it's a private repo. But i've got it working, and will re-insert in `dodgr` straight away. The effect of parallelisation look like this:
![junk](https://user-images.githubusercontent.com/6697851/36541180-5bdd8918-17dd-11e8-9f8f-1ca1c0be362a.png)
Four+four core system, so that's clearly approaching maximal benefit. I was worried that the binary write-read would slow it down too much, but clearly not, which is good to know.

cc @Robinlovelace This is the implementation of parallel flow aggregation. Cracked it!

**Comment by Robinlovelace** [comment]
Awesome.

**Comment by Robinlovelace** [comment]
:+1:

**Comment by Robinlovelace** [comment]
Wow, swift work sir!

**Comment by mpadge** [comment]
Yeah, and it's massively faster!
