### ISSUE TITLE
instructions in main vignette are for 0.2.4 but don't work with 0.2.5

### ISSUE THREAD

**Issue by tbuckl** [ATFutures/dodgr#118]
e.g.

```
net <- dodgr_streetnet (bb)
```

does not run in 0.2.5. 

you probably already know this, might reason for the failing build

**Comment by mpadge** [comment]
Whoops - thanks for finding that

**Comment by mpadge** [comment]
... but then again, it works for me. Do you mean the following lines? Coz they seem fine
``` r
bb <- osmdata::getbb ("york uk")
net <- dodgr_streetnet (bb)
```

**Comment by tbuckl** [comment]
ok right i guess they do work. i think my environment was dated. going through the reprex process made it work.
