### ISSUE TITLE
example in package vignette isn't working anymore

### ISSUE THREAD

**Issue by douglascm** [ATFutures/dodgr#125]
Outputs flow 0 for all links

**Comment by douglascm** [comment]
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- sample (v$id, size = 20)
to <- sample (v$id, size = 50)
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (runif (length (from) * length (to)), dim = c (length (from), length (to)))
length (from); length (to); dim (flows)
#> [1] 20
#> [1] 50
#> [1] 20 50
f <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
sum(f$flow)

gives me 0

**Comment by mpadge** [comment]
I am unable to reproduce that result:
``` r
library (dodgr)
packageVersion ("dodgr")
#> [1] '0.2.5.30'
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- sample (v$id, size = 20)
to <- sample (v$id, size = 50)
d <- dodgr_dists (graph = graph, from = from, to = to)
flows <- array (runif (length (from) * length (to)), dim = c (length (from), length (to)))
f <- dodgr_flows_aggregate (graph = graph, from = from, to = to, flows = flows)
sum(f$flow)
#> [1] 275.2745
summary(f$flow)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#> 0.00000 0.00000 0.01559 0.04609 0.07504 1.31186
```

<sup>Created on 2020-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If you can reproduce via [`reprex::reprex()`](https://reprex.tidyverse.org/), feel free to re-open.
