### ISSUE TITLE
Pairwise distances with dodgr_dists

### ISSUE THREAD

**Issue by agila5** [ATFutures/dodgr#127]
Hi! A friend of mine is working on a project that aims to visualize bike sharing data in Milan and I suggested him to use dodgr and related packages. A few days ago he asked me a question and I'm not sure what's the best answer. Is it possible to calculate pairwise distances using `dodgr_dists`? For example I've always used the following code: 

``` r
# packages
library(dodgr)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

# example
graph <- weight_streetnet(hampi)

set.seed(1)
from <- sample (graph$from_id, size = 100)
to <- sample (graph$to_id, size = 100)
d <- dodgr_dists (graph, from = from, to = to)
dim(d)
#> [1] 100 100
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

that returns a matrix of distances between all points in `from` and all points in `to` while he just wants to know the distance between the first point in `from` and the first point in `to`, the scond point in `from` and the second point in `to` and so on. 

The problem is that if we run the previous code with the full bike data we get the following error: Cannot allocate a vector of size 700GB. I know that we can use a for loop like `for (i in seq_len(n)) res[[i]] <- {dodgr_dists(from[i], to[i])}` or similar approaches but I was wondering what's the suggested way and if you were willing to introduce a pairwise parameter (like in `dodgr_paths`).

**Comment by mpadge** [comment]
huh, yeah, that's a good point. The current answer is, No, that's not possible. Distances are automatically calculated between all combinations of points, and there's no other way to do it. I guess it might sometimes be useful to have just pairwise calculation, and shouldn't be too hard to implement. I'll give it a go and get back to you.

**Comment by mpadge** [comment]
That commit implements a `pairwise` parameter for `dodgr_distances`, which enables this:
``` r
library (dodgr)
packageVersion ("dodgr")
#> [1] '0.2.5.31'
graph <- weight_streetnet (hampi, wt_profile = "foot")
v <- dodgr_vertices (graph)
from <- sample (v$id, size = 20)
to <- sample (v$id, size = 20)
dn <- dodgr_dists (graph = graph, from = from, to = to, pairwise = FALSE)
dim (dn)
#> [1] 20 20
d1 <- dodgr_dists (graph = graph, from = from, to = to, pairwise = TRUE)
dim (d1)
#> [1] 20  1
identical (d1 [, 1], diag (dn))
#> [1] TRUE
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Using `pairwise = TRUE` avoids constructing the huge `nfrom * nto` matrices, so will avoid those `Cannot allocate ...` errors. Only thing to note is that `dodgr_distances()` returns a matrix with both row and column names matching the `from` and `to` IDs, but in this case this can't be done, so a simple *unnamed* matrix with a single row is returned. Let me know how you go

**Comment by agila5** [comment]
Thank you very much for the quick fix but I think that there is something wrong the current implementation. Could you reproduce the following example? I know that it's really a bad reprex but I don't know how to make it simpler. 

``` r
## updates
remotes::install_github("ATFutures/dodgr") # Development version
#> Skipping install of 'dodgr' from a github remote, the SHA1 (43f20b40) has not changed since last install.
#>   Use `force = TRUE` to force installation

# packages
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(dodgr)

# data
bike_data <- read.delim(
  file = url("https://raw.githubusercontent.com/agila5/test_dodgr/master/test_bikes.csv"), 
  header = TRUE, 
  sep = ";"
)

# network of Milan
milan_streetnet <- dodgr_streetnet("Milan, Italy", quiet = FALSE)
#> Issuing query to Overpass API ...
#> Rate limit: 0
#> Query complete!
#> converting OSM data to sf format

# convert to dodgr_object
milan_dodgr_streetnet <- weight_streetnet(milan_streetnet)
#> The following highway types are present in data yet lack corresponding weight_profile values: NA, construction, road, platform, raceway, floor, proposed, emergency_bay, step, crossing, bus_stop, elevator,

# filter nodes that does not belong to the main big component
milan_dodgr_streetnet <- milan_dodgr_streetnet[milan_dodgr_streetnet$component == 1, ]

# saveRDS(milan_dodgr_streetnet, file = "test_dodgr.RDS")
# milan_dodgr_streetnet <- readRDS("test_dodgr.RDS")

# calculate pairwise distances between the first 250 observations. 
bike_distances <- dodgr_distances(
  graph = milan_dodgr_streetnet, 
  from = bike_data[1:250, c("lon_pick_up", "lat_pick_up")], 
  to = bike_data[1:250, c("lon_drop_off", "lat_drop_off")], 
  pairwise = TRUE
)
# the results are quite reasonable
summary(bike_distances)
#>        V1         
#>  Min.   :   0.00  
#>  1st Qu.:   0.00  
#>  Median :  32.94  
#>  Mean   : 362.54  
#>  3rd Qu.: 200.85  
#>  Max.   :5705.59

# calculate pairwise distances between the first 300 observations
bike_distances <- dodgr_distances(
  graph = milan_dodgr_streetnet, 
  from = bike_data[1:300, c("lon_pick_up", "lat_pick_up")], 
  to = bike_data[1:300, c("lon_drop_off", "lat_drop_off")], 
  pairwise = TRUE, 
  quiet = FALSE
)
#> Calculating shortest paths ...
#> done.
# but now the results are totally unreasonable (i.e. the Max value). 
summary(bike_distances)
#>        V1            
#>  Min.   : 0.000e+00  
#>  1st Qu.: 0.000e+00  
#>  Median : 3.000e+01  
#>  Mean   :5.393e+306  
#>  3rd Qu.: 2.010e+02  
#>  Max.   :1.798e+308

# so the problem should lie between 250 and 300, but...
bike_distances <- dodgr_distances(
  graph = milan_dodgr_streetnet, 
  from = bike_data[250:300, c("lon_pick_up", "lat_pick_up")], 
  to = bike_data[250:300, c("lon_drop_off", "lat_drop_off")], 
  pairwise = TRUE
)
summary(bike_distances)
#>        V1         
#>  Min.   :   0.00  
#>  1st Qu.:   0.00  
#>  Median :  10.24  
#>  Mean   : 175.16  
#>  3rd Qu.:  32.63  
#>  Max.   :3001.72

# the same problem does not occurr if I don't use pairwise parameter. 
bike_distances <- dodgr_distances(
  graph = milan_dodgr_streetnet, 
  from = bike_data[1:300, c("lon_pick_up", "lat_pick_up")], 
  to = bike_data[1:300, c("lon_drop_off", "lat_drop_off")], 
  pairwise = FALSE
)
max(bike_distances)
#> [1] 8621.037
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I have no idea what's going on...

**Comment by mpadge** [comment]
Those huge numbers are just machine representations of `.Machine$double.xmax`, and ~~were removed in a commit immediately following the one referenced above.~~  -ah damn, i forgot to push that commit. Now done, so just make sure you've the latext version, which should give
``` r
packageVersion("dodgr")
#> [1] '0.2.5.32'
```
Loading the data you generate above should then give the following:

``` r
library(dodgr)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.3, PROJ 6.2.1
bike_data <- readRDS ("bike_data.Rds")
milan_streetnet <- readRDS ("milano_streetnet.Rds")
milan_dodgr_streetnet <- weight_streetnet(milan_streetnet)
#> The following highway types are present in data yet lack corresponding weight_profile values: NA, construction, road, platform, raceway, floor, proposed, emergency_bay, step, crossing, bus_stop, elevator,
milan_dodgr_streetnet <- milan_dodgr_streetnet[milan_dodgr_streetnet$component == 1, ]

from <- bike_data[, c("lon_pick_up", "lat_pick_up")] 
to <- bike_data[, c("lon_drop_off", "lat_drop_off")] 

system.time (
bike_distances <- dodgr_distances(
                                  graph = milan_dodgr_streetnet, 
                                  from = from,
                                  to = to,
                                  pairwise = FALSE
                                  )
)
#>    user  system elapsed 
#> 182.720   0.956  61.911
summary (as.vector (bike_distances))
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>       0    2420    3617    3803    5094   10860
system.time (
bike_distances <- dodgr_distances(
                                  graph = milan_dodgr_streetnet, 
                                  from = from,
                                  to = to,
                                  pairwise = TRUE
                                  )
)
#>    user  system elapsed 
#>  17.860   0.075   3.609
summary (as.vector (bike_distances))
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#>    0.00    0.00   30.54  373.26  262.59 5705.59      66
```

<sup>Created on 2020-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And `pairwise = TRUE` is even considerably faster (because it uses the A* algorithm, and I guess lots of those points are actually fairly close together so much less of the network is traversed in each case). Please confirm that all is now okay.

**Comment by agila5** [comment]
Thank you very much again. 

> Please confirm that all is now okay.

I will check that tomorrow as soon as I arrive in University.

> I guess lots of those points are actually fairly close together so much less of the network is traversed in each case

Yes, that depends on several errors in the input data but that's not a problem for our application. 

Just one more question: I don't understand the NA values in the `pairwise = TRUE` case because I don't see any `NA` in the other case and, from my understanding, the results of the former case should be like a "subset" (meaning the diagonal of the nxn matrix) of the latter case. Do they depend on the different type of algorithm?

**Comment by mpadge** [comment]
oh yeah, i see what you mean about the `NA` values - I'll check that out tomorrow morning too. Gee, you're sharp!

**Comment by mpadge** [comment]
Hmmm ... there's definitely something strange going on there, but I can't figure out why. It seems to be an `Rcpp::Parallel` issue that I can't work out how to control. I'll re-open and keep digging until I find a solution

**Comment by mpadge** [comment]
Took me a bit to figure that one out, but it was because spatial graphs default to [A* algorithms](https://en.wikipedia.org/wiki/A*_search_algorithm), but with only one point the heuristic search was extending only to the distance of that point and no further, so any points which require going a little out of the way before turning back were not found, giving the pesky `NA` values. That commit just ensures the full search goes a default value of 10% further than the heuristic distance to the search point, with a comment
``` C++
// Arbitrary relative distance threshold
// TODO: Are there likely to be cases where this might need to be adjusted?
```

In spite of that hopefully insignificant hack, the commit now gives the following results:
``` r
library(dodgr)
packageVersion("dodgr")
#> [1] '0.2.5.34'
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.3, PROJ 6.3.0
bike_data <- readRDS ("junk.Rds")
milan_streetnet <- readRDS ("milano.Rds")
milan_dodgr_streetnet <- weight_streetnet(milan_streetnet)
#> The following highway types are present in data yet lack corresponding weight_profile values: NA, construction, road, platform, raceway, floor, proposed, emergency_bay, step, crossing, bus_stop, elevator,
milan_dodgr_streetnet <- milan_dodgr_streetnet[milan_dodgr_streetnet$component == 1, ]

from <- bike_data[1:200, c("lon_pick_up", "lat_pick_up")] 
to <- bike_data[1:200, c("lon_drop_off", "lat_drop_off")] 

system.time (
bike_distances_full <- dodgr_distances(
                                  graph = milan_dodgr_streetnet, 
                                  from = from,
                                  to = to,
                                  pairwise = FALSE
                                  )
)
#>    user  system elapsed 
#>  61.144   0.706  60.925
system.time (
bike_distances <- dodgr_distances(
                                  graph = milan_dodgr_streetnet, 
                                  from = from,
                                  to = to,
                                  pairwise = TRUE
                                  )
)
#>    user  system elapsed 
#>  18.767   0.003  18.802

identical (bike_distances [, 1], diag (bike_distances_full, names = FALSE))
#> [1] TRUE
```

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Also note that the system times aren't realistic there - the first reflects a bunch of initial setting up stuff which is a one-off overhead. When run again, the two are almost identical, because paired values require almost the same computational effort as calculating full matrices. They are nevertheless likely to be useful in cases such as when full matrices can't be held in memory.
