### ISSUE TITLE
dodgr not on CRAN

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/dodgr#133]
See https://github.com/ropensci/stplanr/runs/638416091#step:10:180

Not sure how to get it back there, let me know if you could use a hand testing/debugging.

**Comment by mpadge** [comment]
Yeah, i had tried via email exchange to justify it not being archived, but they obviously determined that my arguments were insufficient. Top priority to get it back up asap

**Comment by mpadge** [comment]
@Robinlovelace There was indeed a C++ :bug: which has now been fixed in the issue linked above. I'll resubmit to CRAN tomorrow.

**Comment by mpadge** [comment]
New version submitted. This issue will be closed as soon as it's up.

**Comment by Robinlovelace** [comment]
Great work Mark.

**Comment by Robinlovelace** [comment]
https://cran.r-project.org/package=dodgr :rocket:
