### ISSUE TITLE
turn restrictions

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#136]
Idea thanks to @edzer during eRum 2020 [Spatial Networks hackathon](https://2020.erum.io/program/hackathon/). The [keys exist in OSM](https://wiki.openstreetmap.org/wiki/Relation:restriction) as relations between ways, yet are currently ignored. An example:
``` r
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
x <- opq ("new york city") %>%
    add_osm_feature (key = "restriction") %>%
    osmdata_sc (quiet = FALSE)
rels <- x$relation_properties
table (rels$value [rels$key == "restriction"])
#> 
#>                                           no_left_turn 
#>                                                   2321 
#>                                          no_right_turn 
#>                                                    583 
#>                                         no_straight_on 
#>                                                     59 
#>                                              no_u_turn 
#>                                                   1856 
#>                                         only_left_turn 
#>                                                     31 
#>                                        only_right_turn 
#>                                                    113 
#>                                       only_straight_on 
#>                                                    313 
#> restriction:conditional=no_left_turn @ (07:00 - 19:00) 
#>                                                      1
```

<sup>Created on 2020-06-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This represents about 2.5% of all junctions in greater New York City (or which there are about 250,000), so such restrictions are quite common, at least there.

@edzer `dodgr` already has code for converting junctions to edge-based representations of in -> out pairs. This is currently used to calculate [time penalties](https://github.com/ATFutures/dodgr/blob/master/src/turn_penalty.cpp) for things like turning across oncoming traffic, but does not yet honour the `restrictions` shown above. Doing so would simply require passing the appropriate restrictions through to the [`replace_junctions` function](https://github.com/ATFutures/dodgr/blob/master/src/turn_penalty.cpp#L101) and excluding these from the resultant compound junction representation.

The only issue would be how to pass these relation data through to the underlying `weight_streetnet` function? It can't be done directly via standard `osmdata` or `sf` representations, so would require either:

1. Passing an additional parameter to `weight_streetnet(..., restrictions)` for when input object is `sc` class; and/or
2. Modifying the [`dodgr_streetnet_sc` function](https://github.com/ATFutures/dodgr/blob/master/R/dodgr-streetnet.R#L72) to append these additional relation data

**Comment by edzer** [comment]
Thanks! For the purpose of routing, you could also make the time penalties very high for the directions that are restricted: not pure, but pragmatic. The U-turn is also an interesting option!

For representing them, you may indeed need to replace the concept of a "junction" node with a set of edges connecting the end points of each of the edges leading up to the junction.

**Comment by mpadge** [comment]
> For representing them, you may indeed need to replace the concept of a "junction" node with a set of edges connecting the end points of each of the edges leading up to the junction.

That's why the C++ function is called `replace_junctions` :wink: And that's why this is all straightforward, because the infrastructure is already there - thanks for the inspiration :+1:

**Comment by mpadge** [comment]
All implemented in that commit, including outright turn prohibitions, as well as restrictions only to permitted directions. Re-opening to document this as part of the [street networks vignette](https://atfutures.github.io/dodgr/articles/times.html).
