### ISSUE TITLE
dodgr_centrality what type of centrality?

### ISSUE THREAD

**Issue by mem48** [ATFutures/dodgr#139]
I might have missed this in the docs for `dodgr_centrality` but is the centrality calculated on the weighted or unweighted graph? If weighted, is it weighted by distance or time?

Would it be possible to choose between the different types?

**Comment by mpadge** [comment]
Oh yeah, that's quite an oversight. That commit implements a `column` parameter on `centrality`:
``` r
library (dodgr)
graph <- weight_streetnet (hampi, wt_profile = "foot")
c_d <- dodgr_centrality(graph, column = "d")
c_dw <- dodgr_centrality(graph, column = "d_weighted")
c_t <- dodgr_centrality(graph, column = "time")
c_tw <- dodgr_centrality(graph, column = "time_weighted")
identical (c_d$centrality, c_dw$centrality)
#> [1] FALSE
identical (c_d$centrality, c_t$centrality)
#> [1] FALSE
identical (c_d$centrality, c_tw$centrality)
#> [1] FALSE
identical (c_dw$centrality, c_t$centrality)
#> [1] FALSE
identical (c_dw$centrality, c_tw$centrality)
#> [1] FALSE
identical (c_t$centrality, c_tw$centrality)
#> [1] FALSE
```

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks as always for the input @mem48. Hope that suffices.
