### ISSUE TITLE
segfault in dodgr_paths

### ISSUE THREAD

**Issue by dcooley** [ATFutures/dodgr#148]
When using `dodgr_paths(..., pairwise = TRUE)` on length-1 from/to vectors we get a segfault

(This example causes a crash)
```r
graph <- weight_streetnet (hampi)
from <- graph$from_id[1234]
to <- graph$to_id[4321]

dp <- dodgr_paths (graph, from = from, to = to, pairwise = TRUE)
```

---

I think [this](https://github.com/ATFutures/dodgr/blob/master/R/paths.R#L101)

```r
for (i in seq (from_index))
```

should be 

```r
for (i in seq_along (from_index))
```

**Comment by mpadge** [comment]
Yep, that was it alright. Thanks!
