### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by polettif** [ATFutures/dodgr#154]
I frequently run into issues with building dodgr from source with xcode on Mac OS (I was reminded by #126). I know how to fix them by now but it's still a hassle especially if it's on a "user" not a "developer" computer. The last CRAN release is from May 2020 and there have been quite some bugfixes since then. Is there a new CRAN release scheduled?

**Comment by mpadge** [comment]
Thanks for the push @polettif. Both [`gtfsrouter`](https://github.com/atfutures/gtfs-router) and this package have undergone some big changes, and both urgently need to be updated on CRAN. And it just happens that i started work on the `dodgr` side of that yesterday, with the closing of several issues. I'll try to get new one submitted today.

**Comment by mpadge** [comment]
v0.2.8 now [on CRAN](https://cran.r-project.org/package=dodgr)

**Comment by polettif** [comment]
👍 thanks!
