### ISSUE TITLE
add plot capabilities

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#17]
implement some kind of plot function that extends from #12 to enable plots like the final vignette one to be auto-generated within `dodgr`. See also #14.

**Comment by mpadge** [comment]
A rough go added via `osmplotr`, but needs to be improved and made more flexible ...

**Comment by agila5** [comment]
Just one random thought: would you be interested in something like `geom_dodgr_streetnet` to plot the result of `weight_streetnet` in a ggplot2 pipe? I could create some examples and, eventually, a PR. I know absolutely nothing about ggplot2 stats and geoms and this would be like an incentive to learn that.

**Comment by mpadge** [comment]
Thanks for the offer, but the working presumption of `dodgr` is that objects are generally way too big to handle via `ggplot`. When implemented, all plotting will work via `mapdeck`, because it's the only system capable of handling 100's of thousands or even millions of edges.

**Comment by agila5** [comment]
Oksoks, nevermind.

**Comment by polettif** [comment]
> When implemented, all plotting will work via `mapdeck`, because it's the only system capable of handling 100's of thousands or even millions of edges.

Just as an FYI, [leafgl](https://github.com/r-spatial/leafgl) can handle that as well.

**Comment by mpadge** [comment]
This package is already in danger of getting too large, so no further plotting routines will be implemented. At most, this issue may be re-visited later to write a vignette.
