### ISSUE TITLE
runtime error when using dodgr_streetnet()

### ISSUE THREAD

**Issue by LeshunXu** [ATFutures/dodgr#174]
Hi, I am new to use dodgr_streetnet() in dodgr package. Does anyone can help me to solve the reported problem? Here is my code:

`myNet <- "oxford uk" %>% osmdata::getbb() %>% dodgr_streetnet(., expand=0)`

The error I got is:

`Error in check_for_error(doc) : General overpass server error; returned:
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL. runtime error: Query timed out in "query" at line 3 after 26 seconds. `

I appreciate for your help!!

**Comment by LeshunXu** [comment]
My supervisor and I find a solution. Here is the solution:

`myNet <- "oxford uk" %>% osmdata::getbb() %>% t() %>% dodgr_streetnet(., expand=0)`
or
`myNet <- "oxford uk" %>% osmdata::getbb() %>% c() %>% dodgr_streetnet(., expand=0)`

So, I think, it would be great if add `bbox <- t(bbox)` before `bb <- process_bbox(bbox, pts, expand)` in the `dodgr_streetnet()` function.

**Comment by MartinLHazelton** [comment]
Thanks @mpadge ! The advantage of getting the bounding box first is that one can subsequently tailor the boundaries to one's requirements.
