### ISSUE TITLE
dodgr_to_sf ---> old-style crs object detected; please recreate object with a recent sf::st_crs()

### ISSUE THREAD

**Issue by Urban-JonathanCohen** [ATFutures/dodgr#183]
Hi there...
there seems to be an issue with the function... i run the example provided in the documentation... 
hw <- weight_streetnet (hampi)
nrow(hw) # 5,729 edges
xy <- dodgr_to_sf (hw)

old-style crs object detected; please recreate object with a recent sf::st_crs()

Im trying to find the place in the source... hopefully ill be back

**Comment by Urban-JonathanCohen** [comment]
it runs anyways...

**Comment by mpadge** [comment]
Thanks @Urban-JonathanCohen, I should update that data anyway, so will happily re-open this issue to fix for you and others.
