### ISSUE TITLE
possible extensions

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#25]
1. Route using nodal properties (including turn geometry) as well as edge properties
2. Multi-objective / multi-criteria SP to allow routing through desirable places such as parks

**Comment by JimShady** [comment]
+1 for route using nodal properties. Also multiple edges between nodes with different weights?

I'm currently building the London Underground network using this package (will share code in due course). It would be nice to have a way for the dodgr_paths function to respect that changing lines (Bakerloo Line to Northern Line) is a 'cost' and that it is better to stay on one line if possible.

**Comment by mpadge** [comment]
That's a great use case for nodal routing! I'll definitely keep that one in mind, along with the usual traffic-lights-or-not.

**Comment by mpadge** [comment]
See also #54

**Comment by mpadge** [comment]
Nodal routing is going to be implemented in [`m4ra` (many-to-many multi-modal router)](https://github.com/atfutures/m4ra), not in `dodgr` itself. @JimShady: `mr4a` is currently a private repo, but I'll be happy to add you as a collaborator if you'd be interested in helping development through using it. Not much dev will happen there until [these bits of `dodgr` dev](https://github.com/ATFutures/dodgr/projects/2), but it will get cracking sometime in the not-too-distant future.

**Comment by JimShady** [comment]
> Nodal routing is going to be implemented in [`m4ra` (many-to-many multi-modal router)](https://github.com/atfutures/m4ra), not in `dodgr` itself. @JimShady: `mr4a` is currently a private repo, but I'll be happy to add you as a collaborator if you'd be interested in helping development through using it. Not much dev will happen there until [these bits of `dodgr` dev](https://github.com/ATFutures/dodgr/projects/2), but it will get cracking sometime in the not-too-distant future.

Sounds good please do @mpadge .
