### ISSUE TITLE
Shortest path error

### ISSUE THREAD

**Issue by chrjangit** [ATFutures/dodgr#33]
I'm trying to find shortest paths, but get error:
```
Error in `*tmp*`[[i]] : 
  attempt to select less than one element in integerOneIndex
```

```
library(data.table)
library(dodgr)
dt <- data.table(from=c("a", "b", "c", "a"), to=c("b", "c", "d", "c"), dist=c(2, 2, 2, 2), weight=c(3, 3, 3, 3))
dp <- dodgr_paths(dt, from="a", to="d")
```
I might have misunderstood how dodgr works...

**Comment by mpadge** [comment]
no, you haven't misunderstood, and yes, you have uncovered a bug there. I'll try to fix that asap (but possibly won't have time until early next year). Thanks for using, thanks for finding this, and thanks for reporting it!

**Comment by mpadge** [comment]
now that's really interesting. The error was ultimately caused by this strange behaviour in R itself:
```
> d <- data.frame (x = letters [1:3], y = letters [4:6])
> c (d$x, d$y)
[1] 1 2 3 1 2 3
```
Those obviously should be letters, not numbers. Should all be good now.
