### ISSUE TITLE
function to insert new vertices

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#40]
Following on from @rafapereirabr's [SO question](https://stackoverflow.com/questions/47598259/add-new-node-to-spatiallinesnetwork-in-stplanr), it would be very useful for `dodgr` to incorporate the ability to insert new points in a network. Current routing can accept arbitrary points, but these are simply mapped to nearest network points and then forgotten. Incorporation of new points would involve modification of the underlying network, so a network with an edge between A and B would be modified through calling
```
insert_point (network, x, y)
```
to
```
A -> (new point with hashed id) -> B
```
or,
```
> insert_point (network, x, y, "C")
# A -> C -> B
```
The points A and B **could** be automatically identified as the nearest two points, yet this may not necessarily be what is desired. It will likely be necessary to have an option to override this default behaviour that would then graphically show the default, yet enable other options to be specified.

@rafapereirabr: this might take a while to implement, because it will be more appropriately incorporated within the soon-to-appear-on-cran [`silicate`](https://github.com/hypertidy/silicate), and associated `sc`, rather than `sf` or `sp` representations. This whole issue is therefore likely to first be shifted to `silicate` and ultimately resolved there. cc @mdsumner

**Comment by rafapereirabr** [comment]
The idea is to add a new node somewhere along an existing edge. One element to consider in this task is the location of the new node, whether it should be placed the halfway the edge or whether it should be placed at a specific location set by the user.  In the case of my SO question, it's the second case, where the user sets a pair of `lat` `long` of the new node.  

Thanks for taking this task on board !

**Comment by JimShady** [comment]
For reference, this code snippet would seem to be useful for this extra functionality:

https://gis.stackexchange.com/questions/288445/split-polyline-by-point-using-sf-package-in-r

**Comment by JimShady** [comment]
> The idea is to add a new node somewhere along an existing edge. One element to consider in this task is the location of the new node, whether it should be placed halfway the edge or whether it should be placed at a specific location set by the user. In the case of my SO question, it's the second case, where the user sets a pair of `lat` `long` of the new node.
> 
> Thanks for taking this task on board !

Just reading this ... the new node should be created at the closest point to the `lat long` specified by the user I would think. That's what I'd expect anyway. Process would be something like this I think:

1. take the origin latitude and longitudes supplied by a user
2. If requested, start the node insertion process
  a. snap origins to nearest edges
  b. snap destinations to nearest edges
  c. split lines and create new lines
  d. rebuild the graph
3. Perform routing

Maybe the `insert_point` enhancement would be an option within the routing functions? Something like `route_dodgr(start_point,end_point, net, create_nodes = TRUE)`

**Comment by mpadge** [comment]
That commit adds a new function `dodgr_insert_vertex()`, which does most of what was discussed above. The one thing is does not do is enable a vertex to be inserted at the intersection of two existing lines, because the new vertices are always assumed to be genuinely new, and bear no relation with pre-existing network structures. But at least it's a good start - Please feel free to give it a try, and comment here.

**Comment by rafapereirabr** [comment]
thanks for the follow up !

**Comment by mpadge** [comment]
Yeah, sorry it took sooooo long! It's still not ideal, but there are a number of alternative paths from here on, so I think it's just best to first spin out this initial version and see what kind of feedback it might generate before moving further with it. Thanks for the impetus! Please give any feedback, insight, suggestions you might have either here, or in new issues.
