### ISSUE TITLE
match data to geometry in dodgr_to_sf

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#44]
`dodgr_to_sf` current just returns geometry, leaving the user to match the contracted geometry onto the flow data from the full (non-contracted) `data.frame`. The `dodgr_to_sf()` function should be modified to return a list of

1. The `_sfc` geometry as in current form; along wiht
2. A modified `data.frame` containing all of the corresponding data re-matched onto the contracted geometry

cc @Robinlovelace

**Comment by Robinlovelace** [comment]
Awesome this has been fixed, look forward to testing it, perhaps in a prototype `route_dodgr()` wrapper for `stplanr`.

**Comment by mpadge** [comment]
I'll leave you @Robinlovelace to open an issue on `stplanr` if you want to go down that path. Happy to contribute more there.
