### ISSUE TITLE
test non-OSM data

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#45]
All current tests are on consistent `osmdata` structures. Tests have to be extended to consider other potential types of data, especially other types of street networks: `splanr::routes_fast_sf`

cc @Robinlovelace

**Comment by chrijo** [comment]
Hi Mark,

is it possible to use network data from other source than osmdata. In my specific case I want to use a street network from an ESRI shapefile (https://www.geofabrik.de/de/data/shapefiles_routable_vienna.zip).

Thank you in advance

chrijo

**Comment by mpadge** [comment]
It should be. I'll try it and paste code here. @Robinlovelace?

**Comment by Robinlovelace** [comment]
LGTM. Should I rejuvenate the 'routes_fast` example?

Contains may overlapping routes that can be aggregated with `stplanr::overline()` and hopefully `dodgr::something()` also.

**Comment by mpadge** [comment]
@Robinlovelace After an extended dev break, `dodgr` is now back in full-swing dev mode, trying to hit as many issues as I can. I've given this one a go, but note here that `overline` and `dodgr::something()` are not really compatible. The `dodgr` view on things is that flows are from point sources, as in the classic transport example of OD matrices. `overline` in contrast, is a **line** aggregation routine.

The newly extended example for `dodgr_flows_aggregate()` done in the above commit uses `stplanr::routes_fast`. Note, however, that what I've done is to separate `stplanr::routes_fast` into the underlying spatial network, plus a matrix of OD values and associated start/end points. This in no way generates comparable results, because `dodgr` still enables flows to be directed anywhere at all, ultimately giving greater dispersal of flows throughout the network, whereas `overline` is merely aggregating the pre-specified flows.

It all works nevertheless, and the result looks something like this:
![screenshot_2018-10-25 screenshot](https://user-images.githubusercontent.com/6697851/47498697-4e7adb80-d85e-11e8-9c80-421bf492d6e2.png)
This just uses uniform values at the start and end points of your `routes_fast` data, and so the aggregated values don't at all reflect what you try to achieve with your `overline` example, but it illustrates the principle, and it works.

**Comment by mpadge** [comment]
(And it's cool to see Chapo assume it's rightfully central place!)

**Comment by Robinlovelace** [comment]
Great progress Mark! Yes good point about overline being about line aggregation rather than routing. Will be interesting to see how this works on larger route networks... Impressive to see it working on basically an spatial line network you give it.
