### ISSUE TITLE
dodgr_dist vs. geographical distance

### ISSUE THREAD

**Issue by chrijo** [ATFutures/dodgr#49]
Hi,

I played around with dodgr_dist to see how the geographical distances and walking distances calculated with dodgr_dist deviate. Normally all walking distances should be greater than or equal to the geographical distances. However, empirically dodgr_dist calculates distances that are shorter. Is it a data / osm problem? Or is my code wrong? Here is my code:

```
library(sf)
library(dodgr)
library(ggplot2)
library(sp)

#creates the graph for Essen
essen <- dodgr_streetnet("Essen, Germany")
graph <- weight_streetnet (essen, wt_profile = "foot")

#creates a rectangle as sample boundery
rec <- as(raster::extent(51.44, 51.475, 6.98, 7.06), "SpatialPolygons")
proj4string(rec) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
e_forty <- fortify(rec)

#sample grid and points
grid <- spsample(e, n = 100, "regular")
plot(grid)
random <- spsample(e, n = 10, "random")
points(random)

from <- as.data.frame(coordinates(grid))
to <- as.data.frame(coordinates(random))

names(from) <- c("lat","lon")
names(to) <- c("lat","lon")

ggplot(graph, aes(x=from_lon, y=from_lat))+geom_segment(aes(xend = to_lon, yend= to_lat))+
  geom_point(data = from,aes(lon, lat), col = "yellow")+
  geom_point(data = to,aes(lon, lat), col = "red")

#network distances from grid points to sample points
net_dist <- dodgr_dists(graph, from = from, to = to)

#minimum network distance
min_net_dist <- apply(dodgr_dists(graph, from = from, to = to), 1,min)

#minimum geographical distance
min_geo_dist <- apply(spDists(as.matrix(from),as.matrix(to), longlat = T), 1, min)

from$diff <- min_net_dist - min_geo_dist
from$neg <- ifelse(diff > 0, 0,1)

ggplot(data = graph, aes(x = from_lon, y = from_lat))+geom_segment(aes(xend=to_lon, yend=to_lat))+
  geom_point(data = from,aes(x = lon, y = lat, colour = diff, size = diff))+
  scale_color_gradient2(low = "blue", high = "red")


ggplot(data = graph, aes(x = from_lon, y = from_lat))+geom_segment(aes(xend=to_lon, yend=to_lat))+
  geom_point(data = from,aes(x = lon, y = lat, colour = as.factor(neg), size = diff))+
  scale_color_discrete()  
```

**Comment by mpadge** [comment]
`dodgr`, as with any other routing engine, has to "snap" any points you give it to the nearest grid points. In these cases, routing will never be between the exact points you feed to `dodgr_dists`, and so routing distances may in fact end up less than direct yet full distances between two points. Trite example shown below, where the red routing points are snapped to the nearest black network points, resulting in a routed distance that is actually less than the direct distance.
![junk](https://user-images.githubusercontent.com/6697851/39133990-d3bf43e2-4715-11e8-825d-1d1f8d485ad1.png)

Routing between random points is always best done by sampling the actual network nodes:
```
v <- dodgr_vertices (net)
pts <- sample (v$id, n = 100) # or whatever
```

**Comment by chrijo** [comment]
So it was my misinterpretation. Thank you very much for the Explanation!

**Comment by mpadge** [comment]
Thanks for using the package!
