### ISSUE TITLE
weight_streetnet does not support railways

### ISSUE THREAD

**Issue by mem48** [ATFutures/dodgr#54]
A feature request:

For a weighting profile for railways taken from the OSM, which respects the max speed variable and the railway variable.

**Comment by mpadge** [comment]
That's a great idea, and also related to #25. I've put in the project stuff [here](https://github.com/ATFutures/dodgr/projects/1)

**Comment by mpadge** [comment]
@mem48 Might need some help and advice here. Main Q is what to do with entries that have no `maxspeed` value? Check my sample:
```
> tb <- names (table (dat$osm_lines$railway))
> tbs <- list ()
> for (i in tb) {
>   indx <- which (dat$osm_lines$railway == i)
>   ti <-  table (dat$osm_lines$maxspeed [indx], useNA = "always")
>   tbs [[length (tbs) + 1]] <-  ti [which (ti > 0)]
> }
> names (tbs) <- tb
> tb
$abandoned

 100   30   50   60   80 <NA> 
   1    2    4    1    4  123 

$disused
<NA> 
  25

$funicular
<NA> 
  20 

$narrow_gauge
<NA> 
  26 

$platform
<NA> 
  17 

$platform_edge
<NA> 
  11 

$proposed

 250 <NA> 
   4   21 

$rail

    100     110     120     130     160      25      40      55      60      65 
     42      67      36      80      10       5     231       1     121       5 
     70      75      80      90      95 signals    <NA> 
      8       4      11      33      62       1     667 

$razed

 100 <NA> 
   9    3 
```
Only standard `"railway" == "rail"` entries appear to have consistent `"maxspeed"` values, but even then only for
```
> indx <- which (dat$osm_lines$railway == "rail")
> length (which (!is.na (dat$osm_lines$maxspeed [indx]))) / length (indx)
0.5180636
```
... just over half of the entries. Moreover, although most categories ought not be associated with `"maxspeed"` values, both `"funicular"` and `"narrow gauge"` ought to be able to be included yet (in this sample) can not because of non-specified values. Advice please?

**Comment by mpadge** [comment]
Actually, it appears the `maxspeed` is just a default inheritance from streets themselves, with the only indication of application to railways coming from the [`"maxspped"` tag entry](https://wiki.openstreetmap.org/wiki/Key:maxspeed) which suggests application to `"railway" = "rail"`, yet none of the other sensible applications (`"funicular"`, `"narrow_gauge"`). Direct advice for railway only suggests the tags (`"electrified", "gauge", "frequency", "voltage", "rack", "bridge", "tunnel"`), yet no mention of `"maxspeed"`.

`"maxspeed"` values must nevertheless be considered sufficiently comprehensive to provide the basis for the [Open Railway Map](https://wiki.openstreetmap.org/wiki/OpenRailwayMap), yet my toy example shows clear inadequacies. What to do ...?

**Comment by JimShady** [comment]
I've not looking at rails in OSM much I'm afraid. Focused mostly on roads, and the London Underground (for which I download nodes and edges and create my own network).

Looking at your examples .... I'm also a bit confused. There's a ton of inconsistencies. Though that's one of the main downsides with using OSM, right. If we're talking in context of using this data for a routable network (we are yes?), then it seems reasonable to use a default value where none exists? I use 33km/h for the London Underground for example. This could be a mean of existing data, or from literature.

**Comment by JimShady** [comment]
(Obviously the ideal solution is to update all the train lines directly in OSM, but failing that....)

**Comment by mem48** [comment]
It appears to be an underdeveloped area of OSM, I suggest looking at:
https://www.openrailwaymap.org/ 
https://wiki.openstreetmap.org/wiki/OpenRailwayMap
who seem to be leading on this. 

You can see that the maxspeed tag is widely but not universally used, although I agree that there does not seem to be official OSM endorsement of this. I'd suggest a default of 60 kph for lines that have NA.  This value is slow of an inter-city train but not unusual for metro or light rail.

**Comment by mpadge** [comment]
@mem48 @JimShady That commit implements a new `weight_railway()` function, with demo in the example code:
```
library (osmdata)
dat <- opq ("shinjuku") \%>\%
    add_osm_feature (key = "railway") \%>\%
    osmdata_sf (quiet = FALSE)
graph <- weight_railway (dat$osm_lines)
```
It defaults to simple weighting by direct distance, and so gives:
```
> head(graph)
  geom_num edge_id    from_id from_lon from_lat      to_id   to_lon   to_lat          d d_weighted highway   way_id component maxspeed
1        1       1 1808422503 139.7253 35.68097  237410747 139.7260 35.68126 0.06827776 0.06827776    rail 22052475         2       95
2        1       2  237410747 139.7260 35.68126 1808422503 139.7253 35.68097 0.06827776 0.06827776    rail 22052475         2       95
3        1       3  237410747 139.7260 35.68126 1574109697 139.7263 35.68142 0.03197353 0.03197353    rail 22052475         2       95
4        1       4 1574109697 139.7263 35.68142  237410747 139.7260 35.68126 0.03197353 0.03197353    rail 22052475         2       95
5        1       5 1574109697 139.7263 35.68142  315862785 139.7265 35.68157 0.02639148 0.02639148    rail 22052475         2       95
6        1       6  315862785 139.7265 35.68157 1574109697 139.7263 35.68142 0.02639148 0.02639148    rail 22052475         2       95

```
But it should then be trivial to re-scale weighted distances according to your own preferences for `maxspeed` or whatever. Is that a good solution?

**Comment by JimShady** [comment]
@mpadge Great work. Five lines of code to get a railway routing network for Shinjuku ! Agreed, relatively simple for users to adjust d_weighted to their own parameters. I'll have a look at how this works in London shortly.

**Comment by JimShady** [comment]
Have a play with this @mpadge 

```
library(dodgr)
library (osmdata)
library(sf)

dat <- opq("london") %>%
  add_osm_feature (key = "railway", value = 'subway') %>%
  osmdata_sf (quiet = FALSE)

dat <- dat$osm_lines

ggplot() + geom_sf(data = dat, aes(colour = line))

dat$maxspeed <- as.numeric((substr(dat$maxspeed, 1, 2)))

dat[is.na(dat$maxspeed),'maxspeed'] <- 15

dat <- dat[,c(1,2,23,25)]

graph <- weight_railway(dat, type_col = 'maxspeed')
```
It breaks near the end. Got to do something else for now but I'll take another look later.

**Comment by mpadge** [comment]
Cool, thanks for quick feedback! The break is just because the `type_col` expects characters. The idea here is to generate the weighted graph, and then only do adjustments like `maxspeed` after the fact. So this would work:
```
graph <- weight_railway (dat, type_col = "line")
graph$d_weighted <- graph$d * max (graph$maxspeed) / graph$maxspeed
```
(where you want slower lines to have greater `d_weighted` values).
