### ISSUE TITLE
Dodgr does not work with the os_roads_bristol example

### ISSUE THREAD

**Issue by mem48** [ATFutures/dodgr#55]
It seems that when using the `weight_streetnet` function dodgr does not join the lines into a complete network but instead just many disconnected subgraphs.

**From the vignette**
```
colnm <- "formOfWay"
wts <- c (0.1, 0.2, 0.8, 1)
names (wts) <- unique (os_roads_bristol [[colnm]])
net <- weight_streetnet (os_roads_bristol, wt_profile = wts,
                         type_col = colnm, id_col = "identifier")
```

**Analysis**
```
nrow(os_roads_bristol)  #29 lines
length(unique(net$component)) #29 discrete subgraphs
```
**Try routing**
```
from <- net$from_id[1:2]
to <- net$to_id[406]
dp <- dodgr_paths (net, from = from, to = to)
```
dodgr fails to find any routes

**Comment by mpadge** [comment]
yeah, it all looks okay by me too - i get a single connected component that can be routed on.
