### ISSUE TITLE
Calc distances with mapbox cheap ruler

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#57]
[Cheap ruler](https://github.com/mapbox/cheap-ruler-cpp) is explained in [this blog post](https://blog.mapbox.com/fast-geodesic-approximations-with-cheap-ruler-106f229ad016). Their cheap method for intra-urban distances would likely provide a nifty speed boost

**Comment by mdsumner** [comment]
So many packages could use this if it were its own tiny package - the closest is geosphere but even that imports sp.  This is one of those core pieces that could really help clean up - were you thinking to incorporate it or make a package? If you incorporate it I'll copy what you do and work on a package in the longer term. :)

**Comment by mpadge** [comment]
I'll incorporate coz it's easier for me to internalize, and also because dodgr is largely C++ and I need to avoid passing back and forth to R. But and so what I'll do is parallel dev of [`geodist`](https://github.com/hypertidy/geodist). Cool with you?

**Comment by mdsumner** [comment]
Great! This will be excellent learning experience for me

**Comment by SymbolixAU** [comment]
Just seen this - have you made any progress on it? 

I ask because I have three R packages (currently private), 

- mapboxGeometry
- mapboxVariant
- mapboxGeojson

and have wanted to implement cheap ruler too. The idea being all communication to cheap ruler will be at the C++ level, not R. So if you haven't moved on this I can open them up and make them actual libraries.

**Comment by mdsumner** [comment]
'cheapruler' is in geodist: https://hypertidy.github.io/geodist/reference/geodist.html

**Comment by SymbolixAU** [comment]
ok cool.

(I might open up the libraries anyway - they may be useful at some point)

**Comment by mdsumner** [comment]
sounds good to me, we're going to need a "registry of interest" for Mapbox libs at some point ;)

**Comment by mpadge** [comment]
@SymbolixAU Make sure to look at the main [`geodist` README](https://github.com/hypertidy/geodist) with ![this figure](https://raw.githubusercontent.com/hypertidy/geodist/master/vignettes/fig1.png) - you have to be sure that your `cheapruler` distances aren't going to exceed a few tens of km. Otherwise C++ code is, for example, [here](https://github.com/hypertidy/geodist)

**Comment by SymbolixAU** [comment]
yep, noted. thanks.

**Comment by mpadge** [comment]
Closing without implementing this because cheapdist may generate inaccurate distances if networks extend beyond ~100km, whereas current elliptical haversine implementation will remain robust. I could port the geodesic code from [`geodist`](https://github.com/hypertidy/geodist/blob/master/src/geodesic.c), but this is not likely to make a huge difference, and keeping Haversine also simplifies licensing here.
