### ISSUE TITLE
Problems with dodgr_paths()

### ISSUE THREAD

**Issue by mem48** [ATFutures/dodgr#61]
I'm having problems getting paths from dodgr_paths()

Example:
```
colnm <- "formOfWay"
wts <- c (0.1, 0.2, 0.8, 1)
names (wts) <- unique (os_roads_bristol [[colnm]])
net <- weight_streetnet (os_roads_bristol, wt_profile = wts,
                         type_col = colnm, id_col = "identifier")

from <- net$from_id[1:2]
to <- net$to_id[6:7]
dp <- dodgr_paths (net, from = from, to = to)
dp
# result
#$`374`
#$`374`$`374-374`
#character(0)
```

dodgr fails to find any paths

I have observed three types of error:

1) Simply Returning an empty list (see above)
2) Error message `Error in dimnames(x) <- dn :   length of 'dimnames' [2] not equal to array extent`

Example:
```
from <- net$from_id[1:2]
to <- net$to_id[406:408]
dp <- dodgr_paths (net, from = from, to = to)
```
3) Returning the wrong route

Example:
```
from <- net$from_id[1:2]
to <- net$to_id[406:407]
dp <- dodgr_paths (net, from = from, to = to)
verts <- dodgr_vertices (net)
path1 <- verts [match (dp [[1]] [[1]], verts$id), ]
points <- verts [match (as.character(c(from,to)), verts$id), ]

plot(path1$x,path1$y)
points(points$x, points$y, col = "red", bg = "red", pch = 21)
```

![rplot](https://user-images.githubusercontent.com/15819577/41468843-31cebd44-70a3-11e8-88d2-78ff91c0c8cd.png)

**Comment by mpadge** [comment]
Thanks @mem48 - `dodgr_paths` is by far the last developed function of the package, coz I don't really have any use cases, and so haven't tested and developed it nearly as thoroughly as the other main functions. As always, your usage and breakage will help greatly. I'll get on to it

**Comment by mem48** [comment]
Glad I can help

**Comment by mpadge** [comment]
Took a ridiculously long time for me to find the very simple cause for that - my previous attempts to be more compliant with non-OSM sources introduced some new lines that inadvertently converted `from_id` and `to_id` values to `integer` instead of `character`. Now fixed, and all of your above examples now work as expected. Thanks as always for continuous improvement!
