### ISSUE TITLE
Use silicate

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#64]
@mdsumner here we go ...

**Comment by mpadge** [comment]
@mdsumner This issue is intended to continue discussion in [this `silicate` issue](https://github.com/hypertidy/silicate/issues/81) without polluting that with too much `dodgr`-speak. I'll copy your code here to allow further explorations here:

```r
to_dodgr <- function(x, ...) {
  UseMethod("to_dodgr")
}
to_dodgr.SC <- function(x, ...) {
  x$object_link_edge %>% dplyr::inner_join(x$edge) %>% 
    dplyr::transmute(from_id = ifelse(native_, .vx0, .vx1), 
                     to_id = ifelse(native_, .vx1, .vx0), d = 1, 
                     edge_id = row_number(), edge_orig = edge_)
}
sc <- SC(routes)

instances <- to_dodgr(sc)
cg <- dodgr_contract_graph(instances)


als <- cg$edge_map  %>%  split(.$edge_new) %>% purrr::map(~ 
                          dplyr::inner_join(.x, instances %>% mutate(edge_id = as.character(edge_id)), c("edge_old" = "edge_id")) 
                                                  )
library(dplyr)
expand_verts <- function(a) {
  a %>% inner_join(sc$vertex, c("from_id" = "vertex_")) %>% dplyr::rename(x0 = x_, y0 = y_) %>% 
  inner_join(sc$vertex, c("to_id" = "vertex_"))
}
plot(sc)
for (i in seq_along(als)) {
  tab <- expand_verts(als[[i]])  
  segments(tab$x0, tab$y0, tab$x_, tab$y_, col = sample(rainbow(length(als)), 1), lwd = 4)
}

points(sc_node(sc) %>% inner_join(sc$vertex) %>% select(x_, y_))
```

The primary incompatibility that is arising in your fab-o code there is the whole issue of directed graphs (see [this cross-issue on `osmdata`](https://github.com/ropensci/osmdata/issues/152)). `dodgr` is strictly intended as a representation of directed graphs, so each edge is interpreted in current `silicate` form as `_native`, meaning a single row with `(from, to, d)` represents uni-directional traversal only. Bi-directional traversal requires a full row repeat

from | to | d
--- | --- | ---
a | b | 1
b | a | 1

This means in turn that a `dodgr` representation can't be directly obtained from simply doing `SC(stplanr::routes_fast_sf)`, because the required duplication is not present. How to solve this is clear; the problem for me as maintainer of both `dodgr` and `osmdata` is where to put the solution? `osmdata` is not the place, because that package is too generic. This would suggest that `dodgr` is the place, and so I've placed this discussion within this issue.

-------

More concretely, I think what the above suggests is that `dodgr` itself simply needs a new method for `weight_streetnet.sc` which takes care of duplication, so I'll open a new sub-issue on that now, and continue to add "master" issue type things here.

**Comment by mdsumner** [comment]
Oh ding dong, I see! Been mulling this 😁

**Comment by mpadge** [comment]
Hey Mike, I'm finally getting fairly seriously on to this. One dumb question: edge properties in SC? `?SC` currently states that it has, "all higher level structures recorded as groupings of edges." Where do fundamental edge properties go? As extra columns in `$edge`? But that violates the "primitiveness" of this object...

**Comment by mdsumner** [comment]
I don't think it violates anything, that's kind of the point - put stuff on the right table, whether a primitives table or a link table.  You're just kind of on your own afterwards ;) Sorry I haven't been able to do anything in this space for a while

**Comment by mpadge** [comment]
Cool, thanks! No worries about no doing - I'm onto it, and hope/plan to be driving (... you to drive ...) silicate towards a stable API sometime soon.

**Comment by mpadge** [comment]
All done now. Output of `osmdata_sc()` can now feed straight into `dodgr::weight_streetnet()`; there's also an internal `dodgr_streetnet_sc()` function to auto-extract `SC`-format networks, and even the possibility of the intermediate addition of elevation data via
```
graph <- dodgr_streetnet_sc("hobart tasmania") %>%
    osmdata::osm_elevation (elev_file = "<local-elevation-file.tiff>") %>%
    weight_streetnet()
```
I had originally thought maybe `silicate` could be used as the **fundamental** representation in `dodgr`, but it still ends up being more efficient to convert to intermediate flat format with each row representing one edge and all associated data - it's much quicker to translate that directly into C++ graph structures that underlie all `dodgr` code. But `silicate` nevertheless now interfaces seamlessly ... just gotta get it on CRAN so it can be used as a dependency.
