### ISSUE TITLE
weight_streetnet.sc method

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#72]
Following on from #64, the currently singular `weight_streetnet` function needs to implement (currently) two distinct methods, `weight_streetnet.sf` and `weight_streetnet.sc`, with both of them taking care of the full necessary duplication of directed edges. Ping @mdsumner

**Comment by mpadge** [comment]
... although, having said that, this actually needs a bit more thing in regard to the ["master" issue](#64), the whole idea of which is to replace the `dodgr::streetnet` format with `sc`/`SC`. As indicated in that issue, and [this `osmdata::osmdata_sc()` issue](https://github.com/ropensci/osmdata/issues/152), the general idea is to use `silicate::SC` as a "master" class to replace current `dodgr` classes, and be able to be submitted directly to all `dodgr` operations. It seems at the moment that the only major thing lacking from such a "master" class is the edge replications needed to represent the directed graph. That in turn suggests that the solution lies in first addressing the [`osmdata` issue](https://github.com/ropensci/osmdata/issues/152), before returning to here. It's hard to see clearly at the moment, but I think this would seem to be the best approach. The only real danger that I can see is that the `osmdata_sc()` function is intended to be as generic as possible, while an extra `dir` parameter is specific only to the potentially restricted subset of street networks. On the other hand, it's called Open **Street** Map for a reason, and street network extraction is likely always going to be the major use of `osmdata`.

**Comment by mdsumner** [comment]
Yep, also toyed with nominated spaces so attribute names could be arbitrary but that is hard.

Just also think about how some data belongs on link or instance tables rather than on a normalized vertex table. Needs more attention ...

**Comment by mpadge** [comment]
This is now implemented, and allows the following:
``` r
library (osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
library (dodgr)
dat <- opq ("omaha nebraska") %>%
    add_osm_feature (key = "highway") %>%
    osmdata_sc ()
elev_dir <- "/data/data/elevation"
elev_file <- list.files (elev_dir, full.names = TRUE)
dat <- osm_elevation (dat, elev_file) # new osmdata fn; currently only on "elevation" branch
#> Loading required namespace: raster
#> Elevation data from Consortium for Spatial Information; see http://srtm.csi.cgiar.org/srtmdata/
system.time (edges <- weight_streetnet (dat, wt_profile = "bicycle"))
#> Loading required namespace: geodist
#> Loading required namespace: dplyr
#>    user  system elapsed 
#>   2.052   0.000   2.055
knitr::kable (head (edges))
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">.vx0</th>
<th style="text-align: left;">.vx1</th>
<th style="text-align: left;">edge_</th>
<th style="text-align: right;">.vx0_x</th>
<th style="text-align: right;">.vx0_y</th>
<th style="text-align: right;">.vx1_x</th>
<th style="text-align: right;">.vx1_y</th>
<th style="text-align: right;">d</th>
<th style="text-align: left;">object_</th>
<th style="text-align: left;">highway</th>
<th style="text-align: left;">oneway</th>
<th style="text-align: left;">oneway_bicycle</th>
<th style="text-align: right;">d_weighted</th>
<th style="text-align: right;">time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1903265686</td>
<td style="text-align: left;">1903265664</td>
<td style="text-align: left;">1dD1JNQCX6</td>
<td style="text-align: right;">-96.18100</td>
<td style="text-align: right;">41.27039</td>
<td style="text-align: right;">-96.18099</td>
<td style="text-align: right;">41.27046</td>
<td style="text-align: right;">7.852440</td>
<td style="text-align: left;">14071785</td>
<td style="text-align: left;">living_street</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">8.265726</td>
<td style="text-align: right;">0.1571181</td>
</tr>
<tr class="even">
<td style="text-align: left;">1903265664</td>
<td style="text-align: left;">1903265638</td>
<td style="text-align: left;">EUC3hhbuNQ</td>
<td style="text-align: right;">-96.18099</td>
<td style="text-align: right;">41.27046</td>
<td style="text-align: right;">-96.18095</td>
<td style="text-align: right;">41.27051</td>
<td style="text-align: right;">6.710915</td>
<td style="text-align: left;">14071785</td>
<td style="text-align: left;">living_street</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">7.064121</td>
<td style="text-align: right;">0.0353206</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1903265638</td>
<td style="text-align: left;">1903265710</td>
<td style="text-align: left;">4SlTXInYcZ</td>
<td style="text-align: right;">-96.18095</td>
<td style="text-align: right;">41.27051</td>
<td style="text-align: right;">-96.18072</td>
<td style="text-align: right;">41.27078</td>
<td style="text-align: right;">35.727600</td>
<td style="text-align: left;">14071785</td>
<td style="text-align: left;">living_street</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">37.608000</td>
<td style="text-align: right;">0.1880400</td>
</tr>
<tr class="even">
<td style="text-align: left;">1903265710</td>
<td style="text-align: left;">1903265636</td>
<td style="text-align: left;">HQpFegxYmu</td>
<td style="text-align: right;">-96.18072</td>
<td style="text-align: right;">41.27078</td>
<td style="text-align: right;">-96.18068</td>
<td style="text-align: right;">41.27083</td>
<td style="text-align: right;">5.805178</td>
<td style="text-align: left;">14071785</td>
<td style="text-align: left;">living_street</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">6.110713</td>
<td style="text-align: right;">0.0305536</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1903265636</td>
<td style="text-align: left;">1903265685</td>
<td style="text-align: left;">q4UUROLOIy</td>
<td style="text-align: right;">-96.18068</td>
<td style="text-align: right;">41.27083</td>
<td style="text-align: right;">-96.18066</td>
<td style="text-align: right;">41.27087</td>
<td style="text-align: right;">5.742714</td>
<td style="text-align: left;">14071785</td>
<td style="text-align: left;">living_street</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">6.044962</td>
<td style="text-align: right;">0.0302248</td>
</tr>
<tr class="even">
<td style="text-align: left;">1903265685</td>
<td style="text-align: left;">1903265678</td>
<td style="text-align: left;">LVMp14Nh3M</td>
<td style="text-align: right;">-96.18066</td>
<td style="text-align: right;">41.27087</td>
<td style="text-align: right;">-96.18063</td>
<td style="text-align: right;">41.27096</td>
<td style="text-align: right;">9.789188</td>
<td style="text-align: left;">14071785</td>
<td style="text-align: left;">living_street</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">10.304408</td>
<td style="text-align: right;">0.0515220</td>
</tr>
</tbody>
</table>

<sup>Created on 2019-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

The whole thing is so much more efficient than `sf` - like at least 5 times faster - and the final `edges` matrix even incorporates slope calculations from the elevation data, and has both distances and times, so the latter can be used for fastest routes.

@mdsumner This represents the primary step towards `dodgr` becoming entirely `silicate`-based. It's so much easier and more efficient than `sf`, and might even move towards dumping `sf` completely and relying instead on our notional ["universal sf-builder"](https://github.com/ropensci/osmdata/issues/157). The code base would be reduced enormously in that case, strongly suggesting it should be done.

@Robinlovelace Time-based routing almost implemented now; will be finished in #76

**Comment by mdsumner** [comment]
Sweeeeet. I made fair progress on cleaning silicate up, gotta get that home!

**Comment by Robinlovelace** [comment]
Great progress indeed.
