### ISSUE TITLE
Mixed observations

### ISSUE THREAD

**Issue by mem48** [ATFutures/dodgr#86]
I've been updating some our or R for Transport Data Science material and adding a new section on dodgr (https://github.com/ITSLeeds/TDS/blob/master/practicals/6-routing.Rmd), so I thought it might be useful to share some observations.

1. There seems to be a bug in `dodgr_to_igraph` in that it insists on 13 columns in the data frame rather than the default 12.
2. A dodgr_to_sf function would be useful to replace the slightly odd dodgr_to_sfc
```
roads <- dodgr::dodgr_to_sfc(streetnet)
roads <- sf::st_sf(cbind(roadss$dat, roads$geometry))
```
3. #17 is a key feature, but being able to go back to SF allows a wide range of plotting options
4. Being able to convert to `igraph` is useful for the analytical abilities in `igraph`, but a function that converts the results back to `dodgr` is needed. In the long term it would be nice to see some of the functions directly in dodgr e.g. edge centrality.
5.  A function to de-contract a graph would be helpful. Contracting speeds up calculation but then makes it hard to transfer findings back to the original street network for plotting.

I've made a first approximation at all of these in the course material. Happy to discuss these further or break into separate issues as needed.

**Comment by mpadge** [comment]
That's great @mem48, they're all really strong ideas. Please, if you like, open 1, 4, and 5 as separate issues. Your 2nd point I've reopened as #7. Thanks as always for insightful input that will help to extend and clarify the package!

**Comment by mpadge** [comment]
Checklist from above

- [x] `dodgr_to_sf()` (#7)
- [ ] :bug: in `dodgr_to_igraph()`
- [ ] `igraph` to `dodgr` function
- [ ] Function to de-contract graphs

**Comment by mpadge** [comment]
Note that the de-contraction (`dodgr_uncontract_graph()`) uses a cached version of the original graph. I'm not sure this is the best approach, and if it is to be kept, then this caching ought to be implemented consistently across all functions that might gain from it. This issue may need to be re-opened to address this.
