### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by Robinlovelace** [ATFutures/dodgr#87]
Not sure this is actually an issue but, in case others find it disconcerting, thought it worth raising. Could there be a less scary message that would provide more useful info about what happened?
E.g.:

``` r
    pts = structure(c(-1.54646277949532, -1.51186137386083, 53.8095165330639, 
                      53.8116109775162), .Dim = c(2L, 2L), .Dimnames = list(c("1", 
                                                                              "1"), c("X", "Y")))
    net <- dodgr::dodgr_streetnet(pts = pts)
    ways_dg <- dodgr::weight_streetnet(net)
#> Warning in `[<-.factor`(`*tmp*`, indx, value = "path"): invalid factor
#> level, NA generated
#> The following highway types are present in data yet lack corresponding weight_profile values: NA,
```

<sup>Created on 2019-03-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mpadge** [comment]
Yep, definitely a :bug: - thanks! Fixing now ...

**Comment by mpadge** [comment]
Oh, actually something that `osmdata` has already fixed. Problem is that the `osmdata` fix is not yet on the CRAN version, so I have to get the new version there. (It just involved ensuring consistent `stringsAsFactors = FALSE` behaviour throughout.)

**Comment by Robinlovelace** [comment]
Aha. Great job, thanks for the quick response!

**Comment by mpadge** [comment]
Also getting on to your `stplanr` code...

**Comment by Robinlovelace** [comment]
Great - heavy refactoring going on in that package. Looking for major release by end of the month so input now: great timing!
