### ISSUE TITLE
dodgr_times function

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#88]
@Robinlovelace This will be a new function that will calculate realistic *times* rather than just distances. In addition to distance dependence, times will also depend on:

1. Slopes
2. Traffic lights
3. Turn angles
4. Crossing multi-lane roads

First Q: Do you know of any standard way to calculate effect of slope? With the latest `osmdata` updates, I've already got slopes in `dodgr`, but need to know how to convert these into (changes in) travel times.

---

Edit: OSM surface data seem to be really improving - I'm working on a completely random US data set (Omaha, Nebraska), and they've got surfaces for > 50% of all ways, including lots of dirt, gravel, unpaved, all sorts. So surface can come in too for both cycling and walking.

Also number of lanes can be included in initial weighted distance calculations, so weighted distances for both cycling and walking are increased with increases in numbers of lanes.

**Comment by Robinlovelace** [comment]
Hey @mpadge I've finally got round to looking at this - getting through backlog! In any case, no, unfortunately I do not know of standard ways to estimate wait time at traffic lights, calculate the 'slowdown' of different turns and hills. However, I have a few ideas on where to start:

- Tags on which different modes are allowed: https://github.com/GIScience/openrouteservice/wiki/Tag-Filtering

Regarding speed profiles for different types of infrastructure/modes I can see this: https://github.com/GIScience/openrouteservice-app/blob/6121e53954468149a28fcaa1aa0a11b45ddbfb51/app/components/ors-profiles-options/ors-profiles-options.html and https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md but not immediately clear where the values are stored...

**Comment by Robinlovelace** [comment]
Update: this is the most detailed profile template I can find. Strange that it's in `.lua` rather than a language agnostic format like `.csv`. Out of interest, @mvl22, what is the best (most accurate for everyday cycling) open access cycling profile you know of and what format is it in? Context: CycleStreets.net has some of the most advanced weighting profiles for cycling out there.

**Comment by chrijo** [comment]
I don't know if this adds to the discussion, however for my purpose I need walking times. Therefore, I'm thinking of using [Tobler's hiking function](https://en.wikipedia.org/wiki/Tobler%27s_hiking_function) to take the slope into account. My workaround would be to add the heights to every node and recalculate the weighted distance using Tobler's hiking function.

**Comment by mpadge** [comment]
Thanks @chrijo. It won't be too long until this is all implemented. In the meantime, you can do it yourself with the following steps:

1. install the `elevation` branch of `osmdata`;
2. use `osmdata::osmdata_sc()` to extract data;
3. Look at info for the `?osmdata_elevation` function for where to get elevation data, and download it locally.
4. use `osmdata_elevation()` to append elevation to the [`SC`-class](https://github.com/hypertidy/silicate) data
5. submit that to `weight_streetnet` to get a street network with distances weighted as usual, but also with an additional `dz` column that quantifies the change in height which you can then use to adjust weighted distances like you suggest.

Hope that helps. I'll update here as things progress ...

**Comment by chrijo** [comment]
Thank you for your detailed answer @mpadge. However, the distances will be quite short. As I understand the open-elevation data has a resolution of 250 m, which is too coarse for my needs. Luckily I have access to a terrainmodell of 10 m resolution.

**Comment by mpadge** [comment]
It's not open-elevation- that project has ceased (but should be resurrected one day soon). The link given in `?osmdata_elevation` will take you to default 90m, but often 30m resolution with global coverage. You can also simply enter the location of your own elevation data file for `osmdata_elevation()` and it should all work.

**Comment by chrijo** [comment]
Thanks @mpadge. Can you please explain the first step to me, because I can't find the function `osmdata_elevation()` in the osmdata (0.0.10) package.
> 1. install the elevation branch of osmdata;

**Comment by mpadge** [comment]
@Robinlovelace That implements all the mechanics for:

1. Wait times at traffic lights
2. Dependence of speed on incline
3. Time penalty for turning across oncoming traffic

The third one entails some [*epic* C++ code](https://github.com/ATFutures/dodgr/blob/master/src/route_times.cpp), but ends up giving what I think is a better solution than many approaches. An initial trial gives results like this:
![junk](https://user-images.githubusercontent.com/6697851/55974756-a7152800-5c88-11e9-8b42-27a02c4f2ed5.png)

There are obviously a couple of remaining issues - a few points suggesting 30km in a few minutes, but it's all coming together. I'll re-open soon with a final checklist to get this to a stable, working state.

**Comment by mpadge** [comment]
@Robinlovelace That implements all the mechanics for:

1. Wait times at traffic lights
2. Dependence of speed on incline
3. Time penalty for turning across oncoming traffic

The third one entails some [*epic* C++ code](https://github.com/ATFutures/dodgr/blob/master/src/route_times.cpp), but ends up giving what I think is a better solution than many approaches. An initial trial gives results like this:
![junk](https://user-images.githubusercontent.com/6697851/55974756-a7152800-5c88-11e9-8b42-27a02c4f2ed5.png)

There are obviously a couple of remaining issues - a few points suggesting 30km in a few minutes, but it's all coming together. I'll re-open soon with a final checklist to get this to a stable, working state.

**Comment by mpadge** [comment]
TODO:
- [ ] implement proper edge duplication for `weight_streetnet(<SC object>)`
- [ ] fix up the final stitching together of turn-angle junctions and the original graph

**Comment by mpadge** [comment]
i think that just about does it:
![junk](https://user-images.githubusercontent.com/6697851/56031150-f0b05200-5d1e-11e9-8d66-d3599679678a.png)

Remaining task:

- [ ] check that times work on contracted graphs

**Comment by mpadge** [comment]
See useful list of links on modelling intersections and turn restrictions [here](https://github.com/bcgov/ols-router/issues/18). Most of these cases are now implemented.

**Comment by Robinlovelace** [comment]
Great work, catching up with GH notifications. Looking good!

**Comment by mpadge** [comment]
This is now all done, but I'll re-open until vignette is finished. Both `dodgr_dists()` and `dodgr_times()` have a `shortest` parameter: `TRUE` routes along *shortest* paths, while `FALSE` routes along fastest paths. The differences are really interesting:

![fig](https://user-images.githubusercontent.com/6697851/56960146-268f6c00-6b50-11e9-8cbf-cf84b3c3b87d.png)

Distances along fastest paths are only sightly longer than distances along shortest; but times along fastest paths are **a lot** faster than times along shortest paths. Those results are generated from a fairly huge network (1,000,000 edges) in a moderately hilly place (total elevation changes a bit over 100m), with times including all possible effects (traffic lights, turn angles, elevation).

**Comment by mpadge** [comment]
code used to generate that for future reference. First, data extraction and processing:
``` r
library (osmdata) # latest dev with `osm_elevation()` fn
library (dodgr)
x <- opq ("omaha nebraska") %>%
    add_osm_feature (key = "highway") %>%
    osmdata_sc ()
elev_file <- list.files ("/data/elevation", full.names = TRUE) # or name of some elevation data file
x <- osmdata::osm_elevation (x, elev_file = elev_file)
graph0 <- weight_streetnet (x, wt_profile = "bicycle") # "base" graph
graph <- weight_streetnet (x, wt_profile = "bicycle", times = TRUE) # junctions re-routed for turn angles
graphc0 <- dodgr_contract_graph (graph0)
v <- dodgr_vertices (graphc0$graph)
set.seed (1)
to <- sample (v$id, size = 100)
from <- sample (v$id, size = 100)

# lines needed at present to map onto full graph with turn angles:
v0 <- gsub ("_start", "", graph$.vx0 [grep ("_start", graph$.vx0)])
v1 <- gsub ("_end", "", graph$.vx1 [grep ("_end", graph$.vx1)])
from [from %in% v0] <- paste0 (from [from %in% v0], "_start")
to [to %in% v1] <- paste0 (to [to %in% v1], "_end")

d0 <- dodgr_dists (graph, from = from, to = to, shortest = TRUE) / 1000
d1 <- dodgr_dists (graph, from = from, to = to, shortest = FALSE) / 1000

t0 <- dodgr_times (graph, from = from, to = to, shortest = TRUE) / 3600
t1 <- dodgr_times (graph, from = from, to = to, shortest = FALSE) / 3600
```

Then the plotting routines:
``` r
dat <- data.frame (x = c (d0, t0),
                   y = c (d1, t1),
                   x2 = c (d0, t0),
                   facet = c (rep ("distance", length (d0)),
                             rep ("time", length (t0))))
library (ggplot2)
library (vapoRwave)
library (extrafont)

delta_d <- formatC (mean (d1 - d0, na.rm = TRUE), format = "f", digits = 2)
delta_d_rel <- formatC (100 * mean ((d1 - d0) / d0, na.rm = TRUE),
                        format = "f", digits = 1)
lab1 <- paste0 ("DISTANCE: fastest is ", delta_d, " km or\n", delta_d_rel,
                "% longer than shortest")
delta_t <- formatC (mean (t0 - t1, na.rm = TRUE), format = "f", digits = 2)
delta_t_rel <- formatC (100 * mean ((t0 - t1) / t1, na.rm = TRUE),
                        format = "f", digits = 1)
lab2 <- paste0 ("TIME: fastest is ", delta_t, " hours or\n", delta_t_rel,
                "% quicker than shortest")
facet_labs <- ggplot2::as_labeller (c (`distance` = lab1, `time` = lab2))

ggplot (dat, aes (x = x, y = y)) +
    geom_point (colour = "orange") +
    geom_line (aes (x = x, y = x2), linetype = "dashed",
               color = "#ff0076", size = 1) +
    labs (x = "shortest", y = "fastest") +
    facet_wrap (~facet, scales = "free", #ncol = 2,
                labeller = facet_labs) +
    new_retro ()

**Comment by Robinlovelace** [comment]
Very interesting. Great work!

**Comment by mpadge** [comment]
Thanks, an FYI for you too @Robinlovelace, that I reckon what we've got here is a great case for ... yet another paper that we can't do until we've done all the others in the pile, but ... The ability to compare fastest versus shortest *en masse*, combined with the database of OSM GPS traces, or even the Uber tracks, would enable arguably a truly comprehensive investigation of the extent to which people actually travel more according to fastest or shortest distances. Just an idea to keep in mind.

**Comment by Robinlovelace** [comment]
👍
