### ISSUE TITLE
reconstruct weighting profiles

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#91]
Convert current flat table of values into list with primary values as current table, but expanded with additional column of average speed, and extra list item quantifying single values for each mode of transport of:

1. waiting time at lights
2. turn penalty

See for comparison [this profile](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua) courtesy of @Robinlovelace for OSRM.

**Comment by Robinlovelace** [comment]
Looks good. What is the profile format going to be? .csv file is simplest I can think of.

**Comment by mpadge** [comment]
It has to be a list, because of multiple irreconcilable tables. Details [here](https://github.com/ATFutures/dodgr/blob/master/data-raw/pkg-data-scripts.Rmd), although that is far from the most transparent way to generate and allow modification of such data. Nevertheless, `dodgr::weighting_profiles` does present a pretty intelligible overview. Thoughts much appreciated

**Comment by Robinlovelace** [comment]
Wondering if there's a language agnostic file format. JSON?

**Comment by mpadge** [comment]
That's a good idea - I'll re-open as prompt to implement that.

**Comment by mpadge** [comment]
@Robinlovelace That adds new fn `write_dodgr_wt_profile()`, which writes to local `.json` file which can then be edited and read back. That'll also give you an idea how complex the weighting has become - i'm pretty confident it has all the detail of OSRM.

**Comment by Robinlovelace** [comment]
Very impressive stuff as always. Can't wait to try this out, especially after my recent tweaks to `route_dodgr()`: https://github.com/ropensci/stplanr/commit/3de1af43585c22f440f5db341e8566c90a6811a7#diff-602a41c1f009a1e6b466d2171dbcf0c1R98
