### ISSUE TITLE
fix tikz pics in vignettes

### ISSUE THREAD

**Issue by mpadge** [ATFutures/dodgr#93]
coz current ones rendered by `pkgdown` do not work!

**Comment by mpadge** [comment]
@yihui Please help! Extending from previous [`tinytex` discussion](https://github.com/yihui/tinytex/commit/992c7e2b4d740ad1f150e2635247a4dffe7ef77f), I've got an additional problem rendering tikz images via pkgdown deployed on travis. The figures do render, they're just all mucked up like [this example](https://atfutures.github.io/dodgr/articles/times.html#the-weight_streetnet-function). There is nothing in the travis output that indicates any problems, but it must be due to some kind of missing LaTeX package. Any suggestions? Or more simply: Do you have or know of any examples of successful `pkgdown` deployment via travis that use your tikz engine?

Note that I have tried explicitly calling `tlmgr install` via `before_install` for both `tikz` -- does not work because `tikz` is not an explicit component of `tlmgr` -- and `pgf`, for which travis simply says, "package already present: pgf". With the full `pgf` package there, rendering `tikz` *should* work, and yet does not ...?

**Comment by yihui** [comment]
Sorry, but I have no idea. Does this problem only occur on Travis? i.e. Did you try to build the pkgdown site locally?

**Comment by mpadge** [comment]
Thanks @yihui, it's only a problem with travis latex packages, local builds are all fine. Straightforward attempt at your suggestion did not work, but I'll keep investigating and report back

**Comment by mpadge** [comment]
Hmm.. It doesn't look like it updates at all, and `path add` fails because the path can't be written (with `sudo`). Any further ideas?

**Comment by znmeb** [comment]
I may be able to reproduce this on Arch Linux - the vignettes don't build here either. I'm trying to troubleshoot using a full native TeXLive install - if that works I'll try to reproduce it with `tinytex`.

**Comment by mpadge** [comment]
Reproducing would be great - I also build on arch, and it works, but I have full TeXlive.

**Comment by znmeb** [comment]
Ah - in that case, let me build a container with whatever OS Travis is running - is that Ubuntu 16.04??

**Comment by znmeb** [comment]
Hmmm ... "Travis CI supports R versions 3.0.3 and above on Linux Precise, Trusty and macOS." "Precise" is Ubuntu 12.04 and "Trusty" is 14.04. Both are theoretically out of long-term support, although I think Trusty got extended for some paying customers.

**Comment by znmeb** [comment]
I can reproduce it in a `rocker/tidyverse` container, so it's not Travis.

```
✔  checking for file ‘/home/rstudio/Projects/dodgr/DESCRIPTION’ ...
─  preparing ‘dodgr’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
E  creating vignettes (2m 8s)
   --- re-building ‘benchmark.Rmd’ using rmarkdown
   --- finished re-building ‘benchmark.Rmd’
   
   --- re-building ‘dodgr.Rmd’ using rmarkdown
   tlmgr search --file --global '/preview.sty'
   Trying to automatically install missing LaTeX packages...
   tlmgr install preview
   tlmgr: package repository http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet (verified)
   [1/1, ??:??/??:??] install: preview [7k]
   running mktexlsr ...
   done running mktexlsr.
   tlmgr: package log updated: /home/rstudio/.TinyTeX/texmf-var/web2c/tlmgr.log
   tlmgr path add
   tlmgr search --file --global '/tikz.sty'
   Trying to automatically install missing LaTeX packages...
   tlmgr install pgf
   tlmgr: package repository http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet (verified)
   [1/2, ??:??/??:??] install: ms [6k]
   [2/2, 00:00/00:00] install: pgf [684k]
   running mktexlsr ...
   done running mktexlsr.
   tlmgr: package log updated: /home/rstudio/.TinyTeX/texmf-var/web2c/tlmgr.log
   tlmgr path add
   tlmgr search --file --global '/xcolor.sty'
   Trying to automatically install missing LaTeX packages...
   tlmgr install xcolor
   tlmgr: package repository http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet (verified)
   [1/1, ??:??/??:??] install: xcolor [17k]
   running mktexlsr ...
   done running mktexlsr.
   tlmgr: package log updated: /home/rstudio/.TinyTeX/texmf-var/web2c/tlmgr.log
   tlmgr path add
   tlmgr install dvisvgm
   tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet (verified)
   [1/2, ??:??/??:??] install: dvisvgm.x86_64-linux [1613k]
   [2/2, 00:02/00:02] install: dvisvgm [1k]
   tlmgr: package log updated: /home/rstudio/.TinyTeX/texmf-var/web2c/tlmgr.log
   tlmgr path add
   sh: 1: dvisvgm: not found
   Warning in system2("dvisvgm", c("-o", shQuote(fig2), fig)) :
     error in running command
   Quitting from lines 38-38 (dodgr.Rmd) 
   Error: processing vignette 'dodgr.Rmd' failed with diagnostics:
   Failed to compile dodgr_files/figure-html/fig1-1.dvi to dodgr_files/figure-html/fig1-1.svg
   --- failed re-building ‘dodgr.Rmd’
   
   --- re-building ‘times.Rmd’ using rmarkdown
   tlmgr install dvisvgm
   tlmgr: package repository http://mirrors.ibiblio.org/pub/mirrors/CTAN/systems/texlive/tlnet (verified)
   tlmgr install: package already present: dvisvgm
   tlmgr path add
   sh: 1: dvisvgm: not found
   Warning in system2("dvisvgm", c("-o", shQuote(fig2), fig)) :
     error in running command
   Quitting from lines 119-119 (times.Rmd) 
   Error: processing vignette 'times.Rmd' failed with diagnostics:
   Failed to compile times_files/figure-html/fig1-1.dvi to times_files/figure-html/fig1-1.svg
   --- failed re-building ‘times.Rmd’
   
   SUMMARY: processing the following files failed:
     ‘dodgr.Rmd’ ‘times.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
```

I generated this by cloning this repo and doing `devtools::install(dependencies = TRUE, build_vignettes = TRUE)`. I had to install a couple of Debian spatial library `-dev` files, but otherwise it's the `rocker/tidyverse` container.

**Comment by mpadge** [comment]
That's great - thanks a load for the insightful input! Could you try installing/updating `dvisvgm` along the lines of what's in current [`.travis.yml`](https://github.com/ATFutures/dodgr/blob/master/.travis.yml)? That's the thing that *should* fix it yet doesn't.

**Comment by znmeb** [comment]
I found a workaround - it looks like the TinyTeX executables aren't in the PATH that Travis is using. I did `sudo ln -sf ~/bin/dvisvgm /usr/local/bin/` and the vignette generation worked.

**Comment by mpadge** [comment]
But the executables are there, because the `tlmgr update` [works as expected](https://travis-ci.org/ATFutures/dodgr/jobs/550164726#L859-L867), as does [`update -all`](https://travis-ci.org/ATFutures/dodgr/jobs/550164726#L1268), which includes [`dvisvgm`](https://travis-ci.org/ATFutures/dodgr/jobs/550164726#L1296). The final [`tlmgr path add` command](https://travis-ci.org/ATFutures/dodgr/jobs/550164726#L1403) doesn't seem to do anything, but since the path is clearly found, that shouldn't matter. My suspicion is that the `pkgdown` ruby stuff somehow resets the paths? Do you want to try a PR into the `.travis.yml`?

**Comment by mpadge** [comment]
>>>>> Uwe Ligges writes:

> Kurt, can you pls take a look at your Debian system?
> Best,
> Uwe

Sure.  Debian in general only allows tlmgr user mode, but even this is
not enabled on the Debian check systems as such additional installations
do in fact violate the CRAN Policy.

Apparently the new dodgr passes ok when Debian package dvisvgm is
installed, so my suggestion is that this gets added to the package
SystemRequirements, and I ensure that this is installed on the Debian
check systems.

Best
-k

> On 01.10.2019 12:40, mark padgham wrote:
>> Dear Uwe and CRAN team,
>>
>> I apologise for my repeated failures to resubmit my recently archived
>> package. One issue seems to be a warning from the Debian check, which
>> has issues with tlmgr. This is related only to the Debian system used to
>> check the package, and not any errors in the package istelf. The
>> packages uses tikz to generate vignette images, which requires `tlmgr
>> path add` and `tlmgr update all` commands. These fail on your Debian
>> system due to "action path not supported in usermode"...
