### ISSUE TITLE
contracted graph documentation

### ISSUE THREAD

**Issue by SymbolixAU** [ATFutures/dodgr#97]
I think the development version of the contracted graph has moved ahead of the documentation slightly. From `?dodgr_contract_graph`

> ### Value
> A list of two items: graph containing contracted version of the original graph, converted to a standardised format, and edge_map, a two-column matrix mapping all newly contracted edges onto corresponding edges in original (uncontracted) graph.

However, I see the value is an extended `data.frame`, not a list of two items

```r
sf_melbourne <- dodgr::dodgr_streetnet( "melbourne" )
graph <- dodgr::weight_streetnet( sf_melbourne, wt_profile = "motorcycle")
graph_c <- dodgr::dodgr_contract_graph( graph = graph )
str( graph_c )

Classes ‘dodgr_streetnet’, ‘dodgr_contracted’ and 'data.frame':	42308 obs. of  15 variables:
 $ geom_num     : num  13645 609 609 15397 13609 ...
 $ edge_id      : chr  "a188987" "a188982" "a188981" "a188980" ...
 $ from_id      : chr  "95562828" "67804724" "67804721" "26476680" ...
 $ from_lon     : num  145 145 145 145 145 ...
 $ from_lat     : num  -37.8 -37.8 -37.8 -37.8 -37.8 ...
 $ to_id        : chr  "202472740" "67804721" "67804724" "1883787496" ...
```

And given this structure, how does one extract the `edge_map`?

---

```r
─ Session info ────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       macOS Mojave 10.14.5        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_AU.UTF-8                 
 ctype    en_AU.UTF-8                 
 tz       Australia/Melbourne         
 date     2019-07-25                  

─ Packages ────────
 ...               
 dodgr        * 0.2.0.004  2019-07-17 [1] Github (ATFutures/dodgr@d8bf3fb)
```

**Comment by mpadge** [comment]
Thanks for picking that up! That commit fixes things up. As for your Q: After much thought given to design, many aspects have now been invisibly and silently dumped to non-exposed cache (and processed via background processes). The design now reflects my assumption that the `edge_map` does not actually need to be exposed. Probably the easiest way to get it if really desired is the internal `get_edge_map` function, but this `reprex` illustrates also shows an alternative, through illustrating how that function actually works:
``` r
library (dodgr)
graph <- weight_streetnet (hampi)
graphc <- dodgr_contract_graph (graph)
ec <- dodgr:::get_edge_map (graphc)
e <- dodgr:::get_edge_map (graph) # that works too, and should give the same result
identical (e, ec)
#> [1] TRUE
f <- list.files (tempdir (), pattern = "edge_map", full.names = TRUE)
hashc <- attr (graphc, "hashc") # hash for the contracted graph
grepl (hashc, f) # must be TRUE, so "f" is the cached edge map
#> [1] TRUE
identical (readRDS (f), e)
#> [1] TRUE
```

<sup>Created on 2019-07-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

All of these design decisions reflect my own subjective needs, so I'd love to hear if your needs differ, and/or if you think there might be better or more preferable ways of handling this. Just let me know!
