### ISSUE TITLE
Wrong figure on times vignette ?

### ISSUE THREAD

**Issue by JimShady** [ATFutures/dodgr#99]
Hi Mark,

I think that the image for Figure 1 on this page is incorrect?

https://atfutures.github.io/dodgr/articles/times.html

Thanks, James

![image](https://user-images.githubusercontent.com/2901470/63093258-62620c00-bf5c-11e9-93f5-bd23952d7a0b.png)

**Comment by mpadge** [comment]
Thanks James, This is coz of #93, which still hasn't been resolved. The image is correct, but the `tikz` rendering fails when deployed via travis, and I still can't find out why. But this is a timely reminder and incentive to return to that issue once again ...

**Comment by JimShady** [comment]
Ah cool. Didn't realise you had noticed it already.
